### ISSUE TITLE
Use dask to parallelize? 

### ISSUE THREAD

**Issue by datnamer** [DEAP/deap#100]
New up and coming project is dask. Provides expression graph, parallel  out of core data structures and easy imperative parallel capabilities. Can do shared memory stuff in concert with numba.

Just an idea:

http://dask.pydata.org/en/latest/

**Comment by fmder** [comment]
Look very interesting. Can you provide a code example using it on the
mailing list? Use the mailing list for comment and github issues for
bug/problems.

2015-10-12 10:15 GMT-04:00 datnamer <notifications@github.com>:
