### ISSUE TITLE
Callback functions

### ISSUE THREAD

**Issue by nikhilkalige** [DEAP/deap#107]
I am not sure if this is right way to do it.. But would it be possible to add a callback function to the algorithms. For example.. 
```python
def algorithms.eaGenerateUpdate(....., callback):
     for ..........:
           .....
           callback()
```
The reason behind this is that you could use it to plot graphs like at the end of each generation rather than waiting till the end of all generation.. Just a thought .

**Comment by fmder** [comment]
The idea here is that you copy content of the algorithm to your own script
and do whatever you want :)

With what you propose it is difficult to know what to pass exactly to the
callback.

2015-11-16 20:19 GMT-08:00 Nikhil Kalige <notifications@github.com>:

**Comment by nikhilkalige** [comment]
@fmder I am using it that way now.. But I just thought it would a nice feature to add.. Let me know if that would be something you think would be a value addition to the lib. I could help with that.

**Comment by fmder** [comment]
Thanks for asking. However, we don't believe such a feature is required.
Thanks again.

2015-11-16 20:25 GMT-08:00 Nikhil Kalige <notifications@github.com>:

**Comment by nbro** [comment]
@fmder This is actually a good request. For example, Keras supports this feature, and I don't see why Deap shouldn't support it too. Advising people to copy, paste and change is basically against what software development and paradigms like OOP were meant for, i.e. automate. In my case, I was trying to pass something to the fitness function at each generation, but I don't see how this could be done without copying, pasting, and changing an existing algorithm. Probably, DEAP could be re-designed to have in mind this type of situation.
