### ISSUE TITLE
mutUniform for real numbers

### ISSUE THREAD

**Issue by raaisa** [DEAP/deap#109]
I am using the deap GA library for curve fitting,so I wanted mutation to be a real number in some range. I know mutUniformInt can do this by adding random number to it but I wanted to know if there is some specific reason why mutUniform is not there for real numbers?

**Comment by fmder** [comment]
You are right, maybe you can propose a PR to do this or use the gaussian
mutation coupled with a boundary decorator.

I'll add this to the 2.0 milestone as it is really easy to implement.

2015-11-27 10:44 GMT-05:00 raaisa <notifications@github.com>:
