### ISSUE TITLE
cxSimulatedBinaryBounded generates complex number (unwanted)

### ISSUE THREAD

**Issue by fmv1992** [DEAP/deap#112]
In the file crossover.py the line  `alpha = 2.0 - beta**-(eta + 1)` generates a complex number when it should not. This gives:
```
if rand <= 1.0 / alpha:
TypeError: unorderable types: float() <= complex()
```

edit:

The error happens only if you input the variables outside the bounds range.

**Comment by fmder** [comment]
Why did you closed this?

Have you found the source of the problem?

2015-12-04 8:04 GMT-05:00 fmv1992 <notifications@github.com>:

**Comment by fmv1992** [comment]
Yes I have found the answer (it is in the edit above).
The function does not verify if the solutions are within the boundaries. You have to take care of this yourself. If you do it works as expected.

**Comment by zhuowang0629** [comment]
Hello,

I know this was posted a long time ago but could you please help me?
I believe my problem is similar:

**Comment by zhuowang0629** [comment]
Hi

I know this was posted a long time ago but could you please help me? I believe my issue is similar:
c2 = min(max(c2, xl), xu)
TypeError: '>' not supported between instances of 'int' and 'complex'
My individuals should be (0,100) so I set the bounds like this but why there is still complex number?
I am very confused.
