### ISSUE TITLE
[RFE] OpenCL support

### ISSUE THREAD

**Issue by UniqueFool** [DEAP/deap#113]
Given that deap is using numpy, what is the recommended way for moving certain computations to the GPU, e.g. using OpenCL/pyOpenCL ?

**Comment by fmder** [comment]
I don't know much on OpenCL, but, IMHO, to have the maximum gain you'd have to evaluate a whole population using a single data transfer. You could rearrange your population into a tensor and rely on well known CPU/GPU tensor librares such as TensorFlow or Theano. I guess that would the way I'd approach the thing without knowing more about your problem.

**Comment by nbro** [comment]
@fmder Why was this closed? I don't know if Deap now supports any kind of parallelism/concurrency, but GAs would definitely benefit from vectorized operations and currency. Check, for example, [this](https://arxiv.org/pdf/1708.03157.pdf). I think you should re-open this issue, as this is an important issue, actually.

**Comment by fmder** [comment]
I completly agree. However, the support should not be implemented in DEAP but in the user code. Therefore the close.
