### ISSUE TITLE
Tournament does not work for minimization problems

### ISSUE THREAD

**Issue by rmuellerb** [DEAP/deap#114]
Dear all,

it seems to me that the tournament selection method ( deap.tools.selection.py: selTournament) does not cover minimisation problems, as:
```python
    chosen = []
        for i in xrange(k):
            aspirants = selRandom(individuals, tournsize)
            chosen.append(max(aspirants, key=attrgetter("fitness")))
    return chosen
```
always selects the "maximum" fitness instead of "max/min" depending on the problem.
In my case this results in a neutralisation of my tournament selection (always maximisation) and other selection mechanisms (parent/survivor...).

Am I right or do I miss an important point?

Best regards,
Robin

**Comment by fmder** [comment]
The internal values on which are compared the fitnesses are pre multiplied
by the weights (negative value in case of minimisation). Thus making the
process of selection independent of the type of optimisation.

Cheers,
François-Michel

2016-01-13 5:50 GMT-05:00 Robin <notifications@github.com>:

**Comment by rmuellerb** [comment]
That was the missing link, thank you!

**Comment by rmuellerb** [comment]
Sorry that I have to add something more:

In case the fitness.values are always weighted while setting the property, the the following comment is wrong, isn't it?
"The (unweighted) fitness can be directly accessed via ``individual.fitness.values``"
(https://github.com/DEAP/deap/blob/master/deap/base.py#L200)

The fitness is always already weighted, right?

**Comment by fmder** [comment]
Yes, we maintain an internal weighted value for comparaison and the
original value for accessing.

2016-01-13 8:24 GMT-05:00 Robin <notifications@github.com>:

**Comment by rmuellerb** [comment]
So in case I write an own EA using alternative tournament functions I need to weight them manually?
Comparisons are done according to the weighted values, in case I access ``object.fitness.values`` I got unweighted values right?

**Comment by fmder** [comment]
No, just use the same comparison as used un the original tournament (or any
other selection).

sorted(individuals, key=attrgetter("fitness"), reverse=True)

will always return the best individual first no matter minimisation or
maximisation.



2016-01-13 8:40 GMT-05:00 Robin <notifications@github.com>:

**Comment by rmuellerb** [comment]
Ok great thank you!
