### ISSUE TITLE
Are there any examples for multiple objects problems in deap?

### ISSUE THREAD

**Issue by Michael728** [DEAP/deap#115]
Hello, I am learning deap to solve two objects problems and want to find good examples to learn.Have any advice? Thank!

**Comment by fmder** [comment]
/deap/examples/ga/knapsack.py
/deap/examples/ga/evoknn.py
http://deap.readthedocs.org/en/master/examples/ga_knapsack.html

Please use the mailing for such questions, the issues are reserved for bug reports.
