### ISSUE TITLE
runtime warnings from examples

### ISSUE THREAD

**Issue by bje-** [DEAP/deap#117]
All of the examples issue runtime warnings like these when parallelised with SCOOP.

[2016-02-09 22:27:19,967] launcher  INFO    Deploying 4 worker(s) over 1 host(s).
[2016-02-09 22:27:19,967] launcher  INFO    Worker distribution: 
[2016-02-09 22:27:19,967] launcher  INFO       127.0.0.1:       3 + origin
/usr/local/lib/python2.7/dist-packages/deap/creator.py:132: RuntimeWarning: A class named 'FitnessMax' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/deap/creator.py:132: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.

**Comment by fmder** [comment]
This looks like the same issue as #108

**Comment by fmder** [comment]
Using https://github.com/soravux/scoop@master resolve this issue see #108 for details.

**Comment by AmineAndam04** [comment]
Try to use 
del creator.FitnessMax
del creator.Individual

**Comment by arthurire** [comment]
> Try to use
> del creator.FitnessMax
> del creator.Individual

Could you please tell me where I should add those codes?

**Comment by soheilhosseini** [comment]
Read this. 
https://scoop.readthedocs.io/en/0.7/examples.html

_The condition on line 7 is a safety barrier that prevents the main program to be executed on every workers. It ensures that the map is issued only by one worker, the root._

You should define all creators in:
 if __name == '__main__'

**Comment by tkoyama010** [comment]
I think it is before creating the new `FitnessMax` and `Individual`.
