### ISSUE TITLE
selBest returns inappropriate individual?

### ISSUE THREAD

**Issue by wojciech-galan** [DEAP/deap#122]
Let's look at the code first:
 ```
import random
 
 from deap import base
 from deap import creator
 from deap import tools
 
 def evaluate(individual):
 	# actually identity function
 	return individual[0], individual[1]
 
 weights=(1.0, -1.0)
 creator.create("Fitness", base.Fitness, weights=weights)
 creator.create("Individual", list, fitness=creator.Fitness)
 
 toolbox = base.Toolbox()
 toolbox.register("attr", random.random)
 toolbox.register("individual", tools.initRepeat, creator.Individual,
                toolbox.attr, n=2)
 toolbox.register("select", tools.selBest, k=1)
 toolbox.register("evaluate", evaluate)
 toolbox.register("population", tools.initRepeat, list, toolbox.individual)
 
 if __name__ == '__main__':
 	pop = toolbox.population(n=4)
 	# Evaluate the entire population
 	fitnesses = list(map(toolbox.evaluate, pop))
 	for ind, fit in zip(pop, fitnesses):
 		ind.fitness.values = fit
 	best = toolbox.select( pop )
 	for p in pop:
 		print p.fitness.values, p.fitness.values[0]*weights[0]+p.fitness.values[1]*weights[1] 
 	print 'best', best[0].fitness.values
```
Here are example results:

> (0.971179464300824, 0.8169212887548502) 0.154258175546
> (0.11469453594471324, 0.17143042017403665) -0.0567358842293
> (0.6387077879870999, 0.2390528212633729) 0.399654966724
> (0.7448970946351373, 0.06972324460097934) 0.675173850034
> best (0.971179464300824, 0.8169212887548502)
I supposed that best values should be (0.7448970946351373, 0.06972324460097934). I have run the code several times and always the vector with biggest first element have been chosen. Then I changed weights to (-1.0, 1.0), and selBest has chosen the vector with smallest first element, when the second seemed to be unnoticed.

Is it real issue or am I doing sth wrong?

**Comment by fmder** [comment]
selBest doesn't know what is the appropriate tradeoff between your
objectives. selBest sorts lexicographically, i.e., first objective then for
equal first objective it sorts according to the second objective and so on.
If you want to sort according to the addition between the two objectives
you have to do so explicitly.

Multi objective selection requires specific selection algorithm such as
Pareto Fronts.

Best regards,
François-Michel



2016-02-27 14:25 GMT-05:00 wojciech-galan <notifications@github.com>:

**Comment by wojciech-galan** [comment]
Dear François-Michel
Thank you for the answer. It seems that I simply misunderstood the tutorial.
Regards,
Wojciech Gałan
