### ISSUE TITLE
Could you add BluePyOpt to the list of projects using DEAP

### ISSUE THREAD

**Issue by wvangeit** [DEAP/deap#123]
Sorry, didn't how else to contact than with a github issue.

At the Blue Brain Project (bluebrain.epfl.ch) we've created a new python package that can be used to optimize parameters in neuroscience. The backend to this is DEAP. Could you add it to the projects on the DEAP page ?

The software is here:
https://github.com/BlueBrain/BluePyOpt

We also have a preprint of a publication on arxiv.org:
Van Geit, W., M. Gevaert, G. Chindemi, C. Rössert, J.-D. Courcol, E. Muller, F. Schürmann, I. Segev, and H. Markram (2016, March). BluePyOpt: Leveraging open source software and cloud infrastructure to optimise model parameters in neuroscience. ArXiv e-prints.
http://arxiv.org/abs/1603.00500

This is a description:
The Blue Brain Python Optimisation Library (BluePyOpt) is an extensible framework for data-driven model parameter optimisation that wraps and standardises several existing open-source tools. It simplifies the task of creating and sharing these optimisations, and the associated techniques and knowledge. This is achieved by abstracting the optimisation and evaluation tasks into various reusable and flexible discrete elements according to established best-practices. Further, BluePyOpt provides methods for setting up both small- and large-scale optimisations on a variety of platforms, ranging from laptops to Linux clusters and cloud-based compute infrastructures. 

(Btw, at the moment we're still using a fork of DEAP with an implementation of the IBEA selector at https://github.com/BlueBrain/deap. We should work on merging this into the DEAP master)

**Comment by fmder** [comment]
I've added your arXiv paper to the list. I'm looking forward to review you IBEA PR :)
