### ISSUE TITLE
in deap: individual is not initialized as specified times

### ISSUE THREAD

**Issue by infyprakash** [DEAP/deap#125]
Hi,
       i am a new to deap python, the individual is not being initialized as specified in the toolbox function. Here is my code:
>>> import random
>>> from deap import base
>>> from deap import tools
>>> from deap import creator
>>> creator.create("Fitness",base.Fitness,weights=(-1.0,-1.0))
>>> creator.create("Individual",set,fitness=creator.Fitness)
>>> list1=[250,500,750,1000]
>>> items={}
>>> NBR_ITEMS=10
>>> for i in range(NBR_ITEMS):
...    items[i]=(i,list1[i%len(list1)])
... 
>>> toolbox=base.Toolbox()
>>> toolbox.register("attr_item",random.randrange,NBR_ITEMS)
>>> toolbox.register("individual",tools.initRepeat,creator.Individual,toolbox.attr_item,5)

while calling toolbox.individual(), the individual is getting initialized variable number of times as follows:

>>> toolbox.individual()
Individual([8, 1, 3, 7])
>>> toolbox.individual()
Individual([8, 9, 2, 7])
>>> toolbox.individual()
Individual([0, 1, 5, 6])
>>> toolbox.individual()
Individual([8, 1, 6, 7])
>>> toolbox.individual()
Individual([0, 1, 2, 5])
>>> toolbox.individual()
Individual([8, 1, 5])

as i have mentioned in toolbox, the individual should be initialized 5 times, but my result is something else, it will be very helpful for me if i will get the answer of my issue,Thanks!!

**Comment by fmder** [comment]
The individual is effectively initialized with 5 values but the result is
put in a set. Thus the resulting size may vary if two values are equal.

2016-03-07 18:10 GMT-05:00 infyprakash <notifications@github.com>:
