### ISSUE TITLE
Function salustowicz_1d in benchmark is wrong

### ISSUE THREAD

**Issue by dros1986** [DEAP/deap#126]
The function should be: f(x) = e^x * x^3 * cos(x) * sin(x) * ( cos(x) * sin^2(x) - 1)
but e^**x** instead is e^**-x** as it's possible to see in the code:
`return exp(-data[0]) * data[0]**3 * cos(data[0]) * sin(data[0]) * (cos(data[0]) * sin(data[0])**2 - 1)`

[Here is the link](http://deap.readthedocs.org/en/master/api/benchmarks.html#deap.benchmarks.gp.salustowicz_1d)

**Comment by fmder** [comment]
You are right. Only the documentation is wrong the code is ok.

2016-03-14 5:29 GMT-04:00 dros1986 <notifications@github.com>:
