### ISSUE TITLE
could some one  provide an example of VRP using deap?

### ISSUE THREAD

**Issue by Michael728** [DEAP/deap#128]
I want to solve VRP(vehicle route problem) and want use deap to deal with the problem,I have the GPS data of the cities,it's better to offer me an example,thanks~

**Comment by fmder** [comment]
This is not an issue, please use the user group to ask this kind of question.

**Comment by Michael728** [comment]
where is the user grop?

**Comment by fmder** [comment]
https://groups.google.com/forum/#!forum/deap-users

2016-03-21 6:22 GMT-04:00 Michael翔 <notifications@github.com>:
