### ISSUE TITLE
Duplicates in ParetoFront

### ISSUE THREAD

**Issue by mightyFredJ** [DEAP/deap#135]
Hi,

I try to use DEAP to solve a multi-objective problem in the geographical field.

Thanks to the docs and examples I was impressed how it was easy to define my own specific Individuals classes and my overall program seems to do the job, but trying to analyse deeply the results I'm confused by the fact that <b>the ParetoFront I passed to the algorithm stores absolutely all the evaluated individuals</b> (aka (N_GEN+1) * POP_SIZE for the eaSimple algorithm) thus having many duplicates.

I tried to configure the _similar_ argument of the ParetoFront creator but it does'nt change anything.
I guessed if it is due to the fact I'm using a personal class as Individuals, but it supports equality tests as I can evaluate it at the end of the computation.

An extract of my code (which uses some nonstandard libraries) looks like this :

```
pop = toolbox.population(n=POP_SIZE)
hof = tools.ParetoFront()
(...)
print('go for {} generations of {} indivs'.format(N_GEN, POP_SIZE)))
pop, logbook = algorithms.eaSimple(pop, toolbox, CX_PB, MUT_PB, N_GEN,
                                   stats=stats, halloffame=hof)

print('\n%d elems in the HallOfFame' % len(hof))

indiv1, indiv2 = hof.items[1:3]
print('indiv1 =', indiv1)
print('indiv2 =', indiv2)
print('eq =', operator.eq(indiv1, indiv2))
```

this provides smth like :
```
go for 10 generations of 10 indivs
(...)
110 itms in the HallOfFame
indiv1 = LINESTRING (701886.2288301125 7065849.055639918, 703153.6886632751 7089050.551639997)
indiv2 = LINESTRING (701886.2288301125 7065849.055639918, 703153.6886632751 7089050.551639997)
eq = True
```

I'm not sure this is an issue, maybe I just misunderstood something, thank you for enlighting me.

Regards

Fred

**Comment by fmder** [comment]
I tried to reproduce the bug with the ga/kursawefct example by setting the
mutation and crossover to identity function, the test is here
<https://gist.github.com/fmder/bb535ce2ff0cdc5e09aa22f7c9c1a587>. However,
I ended up with a 5 individual (all different) hof.

The first check
<https://github.com/DEAP/deap/blob/master/deap/tools/support.py#L625> to
see if two individuals are identical is the test for equal fitness
attribute. That might help you find the bug.

Best regards,
François-Michel


2016-05-12 4:28 GMT-04:00 FredJ <notifications@github.com>:

**Comment by mightyFredJ** [comment]
Merci Jean-Michel for your answer.

After a few tries I discovered that the problem starts with the fitnesses indeed : during my computation this information is lost and then the two individuals are considered as different.

Precisely said the problem is not related to the ParetoFront class but the HallOfFame.insert method (line 551 of support.py 8d28b42 the deepcopy function seems to miscopy the fitness).

Then I think the best procedure is then to close this issue and open a new one if I manage to reproduce the bug in a simple example.

Thank you again,

Frédéric
