### ISSUE TITLE
repeated multiple instances in deap.tools.ParetoFront

### ISSUE THREAD

**Issue by manuparra** [DEAP/deap#137]
Hello, when I use `deap.tools.ParetoFront([similar])`, and update each iteration, I use `update (pop)`, and when I write fitness values I can see that I have a lot of repeated items (same fitness). Is it correct?

**Comment by fmder** [comment]
It is not completely abnormal.

Are they the same in the sense of operator.eq
<https://docs.python.org/3/library/operator.html#operator.eq>? Their might
be a difference at the 100th decimal (or even a float number representation
differences). The similarity is also checks for equal individuals.

2016-05-24 11:01 GMT-04:00 Manuel Parra <notifications@github.com>:

**Comment by manuparra** [comment]
Ok, I understand !, it's not a problem, probably compare function is doing what you saying. I have  distinct individuals (more or less similar),  but same fitness in this cases. Probably, Could be a problem of mine, calculating Scores? o really, some distinct individual have same fitness .
