### ISSUE TITLE
Hall of Fame doesn't have nearly the best individual

### ISSUE THREAD

**Issue by embg** [DEAP/deap#143]
I have code like this:

```
 hof = tools.HallOfFame(1)
 algorithms.eaSimple(pop,
                        toolbox,
                        0.2,
                        0.4,
                        10,
                        stats,
                        halloffame=hof)
    print(evaluate(hof[0]))
```

This prints out

```
gen nevals  avg std min         max         
0   300     inf inf 0.000986397 1.79769e+308
1   140     1.75025e+295    inf 0.000986397 5.25076e+297
2   158     1.17532e+07     1.36345e+08 0.000986397 2.09135e+09 
3   172     inf             inf         0.000986397 1.79769e+308
4   148     1.79625e+100    3.106e+101  0.000152741 5.38874e+102
5   169     5.99231e+305    inf         0.000152741 1.79769e+308
6   141     5.12299e+118    6.72516e+119    0.000152741 1.0715e+121 
7   166     2.27081e+179    inf             8.6989e-05  3.40843e+181
8   152     inf             inf             8.6989e-05  1.79769e+308
9   147     1.28411e+157    inf             8.6989e-05  3.85234e+159
10  148     5.99231e+305    inf             8.6989e-05  1.79769e+308
(2562.8788109209804,)
```

So as you can see, the best individual has fitness e-05, but hof[0] has fitness 2562. What's going on???

**Comment by fmder** [comment]
I cannot reproduce your bug with the current master and any example. You'll have to provide a little bit more code that reproduce the bug.

**Comment by duskeralte** [comment]
Check your code with this one

https://github.com/scoliann/GeneticAlgorithmFeatureSelection/blob/master/gaFeatureSelectionExample.py

**Comment by agreenwalrus** [comment]
I met the same problem.
All that I was able to find out  - that problem is related to Statistic.


I wrote these rows in evaluation function:

>  if (t_conflict, r_conflict, f_conflict, f_window, f_start) == (0.0, 0.0, 0.0, 0.0, 0.0, 0.0):
        print("WOW")

    return t_conflict, r_conflict, f_conflict, f_window, f_start

And see log below after running code:
![изображение](https://user-images.githubusercontent.com/26038101/54637467-c2ca4b80-4a99-11e9-9ee2-89333d3295f1.png)

nothing happens. There's no output 'WOW', however, I see 0,0,0,0,0 as minimum in log

**Comment by fmder** [comment]
The min reported is not per individual but per dimension in multi objective.
