### ISSUE TITLE
Index Error in NSGA-II related Tournament selection

### ISSUE THREAD

**Issue by heinfa** [DEAP/deap#146]
It seems to me, that there is some flaw in the method tools.emo.selTournamentDCD. I tried it with a population size of 25 and a "k" value equal to population size. The methods quits with an index error, when reaching the last index (24). This is because the next 3 individuals are also used in this method.

The problem might be related to the xrange built-in function:

> > > for i in xrange(0, 25, 4):
> > > ...     print i
> > > ... 
> > > 0
> > > 4
> > > 8
> > > 12
> > > 16
> > > 20
> > > 24

My Python version is 2.7.1.

**Comment by fmder** [comment]
The nsga2 example and selTournamentDCD are directly from Deb's paper. The
population size must be a multiple of 4.

Best regards,


2016-07-20 9:29 GMT-04:00 heinfa <notifications@github.com>:
