### ISSUE TITLE
Show values for best individual during evolution

### ISSUE THREAD

**Issue by lodenrogue** [DEAP/deap#150]
Is there a way to print or save the best individual while the algorithm is running? Perhaps every nth iteration?

**Comment by fmder** [comment]
Just pickle it to a file in your main loop.

2016-08-28 0:52 GMT-04:00 Miguel Hernandez <notifications@github.com>:

**Comment by lodenrogue** [comment]
I'm not sure how to do this. This is what my main looks like:

        pop = self.toolbox.population(n=10)
        hof = tools.HallOfFame(1)
        stats = tools.Statistics(lambda ind: ind.fitness.values)
        stats.register("min", np.min)

        algorithms.eaSimple(pop, self.toolbox, cxpb=0.5, mutpb=0.5, ngen=50, stats=stats, halloffame=hof, verbose=False)
        return hof[0]

**Comment by fmder** [comment]
You will have to expand eaSimple. Just look at the code in the algorithm
module and add the necessary code in the main loop.

Please for further questions use the mailing list. The github issues are
for bug and enhancement.

Regards
