### ISSUE TITLE
Can I give a starting population

### ISSUE THREAD

**Issue by lodenrogue** [DEAP/deap#151]
Can I manually set a starting population before the algorithm runs?

**Comment by fmder** [comment]
Yes, you can generate the population the way you like random or not.

**Comment by lodenrogue** [comment]
How do I do this? I can't seem to find the explanation in the documentation

**Comment by DMTSource** [comment]
http://deap.readthedocs.io/en/master/tutorials/basic/part1.html?highlight=seeding#seeding-a-population

**Comment by lodenrogue** [comment]
Oh excellent! Thank you @DMTSource
