### ISSUE TITLE
Best individual dying off

### ISSUE THREAD

**Issue by lodenrogue** [DEAP/deap#153]
I am reviewing my results in verbose mode and I can see that the best individual in some generations is worse than the individual in the previous generation. Why is the best individual getting killed off?

Example (note that smaller is better in this example): 

| gen | nevals | min     |
|-----|--------|---------|
| 0   | 10     | 337.706 |
| 1   | 8      | 1182.22 |
| 2   | 7      | 1182.22 |
| 3   | 7      | 1182.22 |
| 4   | 10     | 1182.22 |
| 5   | 10     | 347.904 |
| 6   | 8      | 347.904 |

The best individual in the first generation is not the best individual in the second generation. The fitness weights are (-1.0,)

**Comment by fmder** [comment]
This is absolutly possible and I would add desirable. You observe the
effect of stochastic selection (tournament or roulette) . At the begin of
the evolution the effect is somewhat big as you haven't converged yet, but
at the end of the evolution you wish this happens as it will help you
escape local optima.

The solution to loosing the best individual is to copy the best solution in
an archive while letting the evolution continue in a (yet) sub suboptimal
region. Im DEAP, this archive is called the hall of fame.

Other solution include using deterministic selection such as selBest or
increasing the tournament size.

Best regards,

**Comment by lodenrogue** [comment]
Thank you
