### ISSUE TITLE
How to get the fitness of an individual during crossover

### ISSUE THREAD

**Issue by JakeCowton** [DEAP/deap#154]
I have an idea for my own crossover algorithm and I'd like to implement it using DEAP. How can I get the fitness of each individual within the crossover function?

**Comment by fmder** [comment]
Individual.fitness.values

Some might have none if they were invalidated.

**Comment by JakeCowton** [comment]
Following up...how can I know if those values are to be maximised or minimised?

**Comment by fmder** [comment]
Individual.fitness.weights

2016-10-27 21:31 GMT-04:00 Jake Cowton <notifications@github.com>:
