### ISSUE TITLE
AttributeError: 'list' object has no attribute 'arity'

### ISSUE THREAD

**Issue by StuartFarmer** [DEAP/deap#161]
When attempting to set gp.PrimitiveTree objects in an individual that features a list of them, I get an AttributeError: 'list' object has no attribute 'arity'.

This is my code for the custom crossover:

`def tuple_crossover(ind1, ind2):
    ind1[0], ind2[0] = tools.cxOnePoint(ind1[0], ind2[0])
    ind1[1], ind2[1] = tools.cxOnePoint(ind1[1], ind2[1])
    return ind1, ind2`

**Comment by fmder** [comment]
Have you tried to use tools.gp.cxOnePoint?
