### ISSUE TITLE
SyntaxError: more than 255 arguments

### ISSUE THREAD

**Issue by hfl15** [DEAP/deap#170]
The "SyntaxError: more than 255 arguments" occur when the number of inputs exceed 255. How can I fit that problem? Thank you very much!

**Comment by fmder** [comment]
255 arguments is quite a lot! How did you get to that much? What is the context? This is a know limitation of python : http://stackoverflow.com/a/8932175/873128

**Comment by hfl15** [comment]
Thank you for your replay. I want to distill the non-linear behavior of dynamic system by some sensor time-series. The number of time-series is around 15, but before developing symbolic regression I take time-delay embedding to expand the state space so that the number of variables exceed the limitation of python 255. How can I figure out that problem? I think if the Deap package can accept variables which are encapsulated by array rather than variable-length parameter the problem will be handled.

**Comment by fmder** [comment]
Yes deap handles numpy arrays

**Comment by hossein-pourbozorg** [comment]
next python can be passed this issue:
https://bugs.python.org/issue12844
https://hg.python.org/cpython/rev/5c1bb72c0f5d
