### ISSUE TITLE
Pareto Domination Tournament in the NSGA2

### ISSUE THREAD

**Issue by Dsaqui** [DEAP/deap#171]
Why do you use the Pareto Domination Tournament in the NSGA2 example for selectiong and not the original selection algorithm (binary tournament selection)?

**Comment by fmder** [comment]
The examples/ga/nsga2.py example uses both TournamentDCD and Pareto+Sorting distance selection as described in the original paper.

**Comment by Dsaqui** [comment]
It is based on the paper:A Fast and Elitist Multiobjective Genetic Algorithm: NSGA-II?

**Comment by fmder** [comment]
This one exactly 

Deb, Pratab, Agarwal, and Meyarivan, “A fast elitist non-dominated sorting genetic algorithm for multi-objective optimization: NSGA-II”, 2002.

We used the example to benchmark our nsga-2 selection. We obtained similar results as reported in the paper for convergence and diversity. To test it just enable the code sections in the __main__ at the bottom of the file.

**Comment by Dsaqui** [comment]
Thanks
