### ISSUE TITLE
can you train neural network with DEAP

### ISSUE THREAD

**Issue by zardaloop** [DEAP/deap#173]
HI guys it is not a right place to ask this question but I couldn't think of any better place to ask this question. Did any of you guys did any example of training a neural network using DEAP? 

I would highly appreciate if someone could advise me how to do that and point me into the right direction.

**Comment by fmder** [comment]
The best place for this kind of question is on [the mailing list](https://groups.google.com/forum/?fromgroups#!forum/deap-users)
