### ISSUE TITLE
Python Deap Lib TypeError while compiling fitness

### ISSUE THREAD

**Issue by lumy** [DEAP/deap#176]
I'm getting this exception with my python software (i'm running under windows):

    File "C:\Users\lumy\PycharmProjects\EternityPuzzle\puzzle.py", line 94, in log_stats
      self.record = self.stats.compile(self.population)
    File "C:\Python27\lib\site-packages\deap\tools\support.py", line 237, in compile
      record[name] = stats.compile(data)
    File "C:\Python27\lib\site-packages\deap\tools\support.py", line 204, in compile
      values = tuple(self.key(elem) for elem in data)
    File "C:\Python27\lib\site-packages\deap\tools\support.py", line 204, in <genexpr>
      values = tuple(self.key(elem) for elem in data)
    File "C:\Users\lumy\PycharmProjects\EternityPuzzle\puzzle.py", line 73, in <lambda>
      stats2 = tools.Statistics(key=lambda ind: ind.fitness_group.values)
    File "C:\Python27\lib\site-packages\deap\base.py", line 181, in getValues
      return tuple(map(truediv, self.wvalues, self.weights))
    TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

I was trying to log two differents fitness.

so the getValues function is in the Fitness Object:

    def getValues(self):
        print self.wvalues, self.weights
        return tuple(map(truediv, self.wvalues, self.weights))

Output:

    () (1.0,)

If I understand, wvalues should contains all the old values, but it's seems to be empty the first time and.
My Code sample looks like:

     from deap import base
     from deap import creator
     from deap import tools

     creator.create("FitnessInd", base.Fitness, weights=(1.0,))
     creator.create("FitnessGroup", base.Fitness, weights=(1.0,))
     creator.create("Individual", ind.Ind, fitness_ind=creator.FitnessInd, fitness_group=creator.FitnessGroup)
     toolbox.register("new_individual", creator.Individual)
     toolbox.register("desk", tools.initRepeat, list, toolbox.new_individual)
     population = toolbox.desk(n=len(arr))
     stats2 = tools.Statistics(key=lambda ind: ind.fitness_group.values)
     stats1 = tools.Statistics(key=lambda ind: ind.fitness_ind.values)
     stats = tools.MultiStatistics(fitness_ind=stats1, fitness_group=stats2)
     stats.register("min", min)
     logbook = tools.Logbook()

     values = eval_solution(population)
     for ind, v in zip(population, values):
       ind.fitness_ind.value = v,
       ind.fitness_group.value = v,

     record = stats.compile(population)

Not sure what i'm doing wrong.

**Comment by fmder** [comment]
I think your individual has never been evaluated.

**Comment by lumy** [comment]
So What am i doing at this part of the code ? if it's not an evaluation and an assignation: 

    values = eval_solution(population)
     for ind, v in zip(population, values):
         ind.fitness_ind.value = v,
         ind.fitness_group.value = v,

**Comment by fmder** [comment]
The error appears at line 94 which is not in the code you provided. It is
when you compile the stats for self.population.

**Comment by lumy** [comment]
I'm not gonna copy past thw whole project, if you want have a look we have a github.
So I know the line 94 isn't from my code. That's my question, Why deap can't start to compile the stats ?
I've evaluated my population put the fitnesses into the fitnesses attributes, why is it making me an error the first time ?

**Comment by fmder** [comment]
What branch/version are you on? Line 94 does not correspond to master nor
the lumy branch.

2017-02-02 7:09 GMT-05:00 Lumy <notifications@github.com>:

**Comment by lumy** [comment]
Oh yeah sorry not the right branch https://github.com/lumy/EternityII/blob/cleaner/puzzle.py
Thanks for the help.

**Comment by fmder** [comment]
I'm a little bit "puzzled" here. The code you sent in your first mail
references a population variable that I assume is in your script. I also
assume you import the puzzle.py file in that same script then you
instanciate a Puzzle and call my_puzzle.log_stats(). However, the log_stats
method does not access your population; it accesses the internal population
of the puzzle (self.population) which in my opinion has never been
evaluated. In my understanding, you need to use all the methods from your
Puzzle not variable in your script. Something like that should work (I have
not studied the whole Puzzle class):

my_puzzle = Puzzle(...)
my_puzzle.evaluate()
my_puzzle.log_stats()

Best regards,

2017-02-02 9:23 GMT-05:00 Lumy <notifications@github.com>:

**Comment by lumy** [comment]
Hello,

Thanks for the help,
The first code sample provided wasn't at all the true code.
I just took the important part of the code to show what is happening.

Going through my main function i get an Puzzle object:

    def loop(puzzle):
      for i in range(0, config.NGEN):
        puzzle.evaluate()
        mutated = []
        puzzle.log_stats(i, len(mutated))
    save_population(puzzle)

    def main():
      puzzle = load_population()
      loop(puzzle)

so my population get evaluated before i call stat.compile.

Thanks
Best Regards
