### ISSUE TITLE
gp.cxOnePoint exposes random behavior

### ISSUE THREAD

**Issue by PG-TUe** [DEAP/deap#177]
Hi,

I want to report a bug where `gp.cxOnePoint` exposes random behavior.
When given the same two individuals, and seed, the resulting individuals will not always be the same.
I came across this problem as I was working on [TPOT](https://github.com/rhiever/tpot), where I found the same experiment would not always get me the same result.

Through logging I found the problem to be with `gp.cxOnePoint`, specifically [lines 657 and 660](https://github.com/DEAP/deap/blob/master/deap/gp.py#L657-L660).
The `common_types` set is not always ordered the same (this is allowed by the python specs).
Meaning that while `random.choice` will pick the same index, the actual type on that index might be different.

I tried to capture this in a minimal experiment, but unfortunately I could not create one that reproduced the issue.
I'm not sure what is special about TPOT's code to make the intersection behave more volatile than for my minimal examples.

The solution of course would be to either calculate the set intersection yourself and store it in a list directly, or to sort the list after calculating the intersection.

**Comment by fmder** [comment]
Thanks for reporting. I've started a PR #179 that corrects the problem. We will decide if its shall be included in the master right now or in a future release.

**Comment by PG-TUe** [comment]
No problem, good to hear! I'll close the issue since it a fix make its way to the master branch (eventually).
