### ISSUE TITLE
How to find the population during evolution in genetic algorithm in DEAP python module? 

### ISSUE THREAD

**Issue by vipul1994** [DEAP/deap#180]
I am trying to implement a genetic algorithm through DEAP python module. The fitness function for an individual depends on the other individuals which are also present in the population at that point.

How can I get the complete population in list format at a certain point of evolution and use it in a evaluation method?

**Comment by fmder** [comment]
This is not possible using the one line algorithms (eaSimple, etc.). You will have to implement your own algorithm. Copy paste the original algorithm from DEAP and simply add the desired arguments to your evaluation function.

**Comment by Ginfung** [comment]
Let me clarify @vipul1994 's request: you want to make the current population as one of parameter in your fitness function. right?

**Comment by vipul1994** [comment]
@Ginfung Yes
@fmder Thanks for the suggestion. did it.
