### ISSUE TITLE
Publications avec DEAP

### ISSUE THREAD

**Issue by bbrangeo** [DEAP/deap#183]
Bonjour,

Nous avons publié deux articles avec DEAP 👍 
http://www.ibpsa.org/proceedings/BSO2016/p1108.pdf
http://www.sciencedirect.com/science/article/pii/S0926580516301339

Bonne journée.

Boris BRANGEON

**Comment by fmder** [comment]
Pourriez-vous remplir un Pull Request modifiant le README.md?
