### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by tyarkoni** [DEAP/deap#184]
The current PyPI release is quite out of date (May 2015). Any chance of an update? On several occasions now I've found that the PyPI release doesn't support features in the documentation. (Pip installing from git is not a big deal, of course, but it's a bit annoying to have to go look up the repo address each time, and naive users may not understand what's going on.)

**Comment by fmder** [comment]
It should be coming soon, I'll take time to release at least 1.2.

**Comment by fmder** [comment]
I did it! 1.2.0 is out.
