### ISSUE TITLE
GA Terminators for DEAP

### ISSUE THREAD

**Issue by JIMENOFONSECA** [DEAP/deap#187]
Hi There, great work of you guys of DEAP.

I was wondering if there are any terminators planned for GAs like NSGA-II. 

On the other hand, Is the hypervolume benchmarking function going to be available in the next version, when could we expect another release in PyPI?

thanks,

**Comment by fmder** [comment]
What do you mean by terminators?

Simplistic algorithm (encapsulated in functions) have only the number of
generation termination criterion. To change that one must implement its own
function.

Hypervolume measure is already available on the master branch on github. We
should be able to make a realease shortly.
