### ISSUE TITLE
Possible ParetoFront.update improvement

### ISSUE THREAD

**Issue by lafrech** [DEAP/deap#189]
I was having a look at [`ParetoFront.update`](https://github.com/DEAP/deap/blob/043862cc70c210f3ea6f61115442685cb3280e07/deap/tools/support.py#L606) and I think I have an improvement suggestion.

```python
        for ind in population:
            is_dominated = False
            dominates_one = False
            has_twin = False
            to_remove = []
            for i, hofer in enumerate(self):    # hofer = hall of famer
                if not dominates_one and not has_twin and hofer.fitness.dominates(ind.fitness):
                    is_dominated = True
                    break
                elif ind.fitness.dominates(hofer.fitness):
                    dominates_one = True
                    to_remove.append(i)
                elif ind.fitness == hofer.fitness and self.similar(ind, hofer):
                    has_twin = True
                    break
```

In this version, I added a  `dominates_one` boolean that is set as soon as the new individual dominates an individual in the hall of fame.

There is no point checking that the new individual is dominated as soon as it has dominated or found a twin in the HAF, so if `dominates_one` or `has_twin` is `True`, the first test can be skipped. Testing those two booleans should be faster than tester fitness domination itself.

I hope I'm making sense...

**Comment by fmder** [comment]
Can you propose a PR?

**Comment by lafrech** [comment]
Closed by https://github.com/DEAP/deap/pull/213.
