### ISSUE TITLE
How to update the strategies 

### ISSUE THREAD

**Issue by Marryli** [DEAP/deap#192]
I want to use DEAP. But I put it into CNN，where my strategies are different ,how can I do? Where I can update the strategies?Thanks!

**Comment by fmder** [comment]
What is CNN? What strategies? Can you provide anymore details?

**Comment by Marryli** [comment]
Yeah! CNN is the short of "convolutional neural network". I want to use the strategies,for example ,to add a layer.

**Comment by fmder** [comment]
Ok, I had to look up your repositories to find out what you were talking about. I didn't wrote that article, nor any developper of DEAP. However, it should be pretty straight forward to realize this with DEAP and you should give it a shot.

As this is not an actual issue with DEAP I'll just close it.
