### ISSUE TITLE
The C extensions could not be compiled, speedups won't be available

### ISSUE THREAD

**Issue by joanrocagas** [DEAP/deap#196]
The windows setup from source outputs the following warning:

 ***************************************************************************
    WARNING: The C extensions could not be compiled, speedups won't be available.
    Plain-Python installation succeeded.
    ***************************************************************************

How can we fix this? are these speedups important?

**Comment by fmder** [comment]
It is only for hypervolume computation.

You need to have a C/C++ compiler on your path. On Windows, this would be MinGW.
