### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by lmarti** [DEAP/deap#197]
There is a lot of new stuff in the repository that is not available doing a pip install. It would be great if you make a new release.

**Comment by hossein-pourbozorg** [comment]
You can install latest version of DEAP by typing the command:
```
python3 -m pip install -U https://github.com/DEAP/deap/archive/master.zip
```
to the shell.

**Comment by fmder** [comment]
or

pip install git+https://github.com/DEAP/deap@master

but yeah a release is long overdue!



2017-05-05 3:52 GMT-04:00 Hossein Pourbozorg <notifications@github.com>:

**Comment by lmarti** [comment]
@hossein-pourbozorg and @fmder yes, of course and also `git clone` and `python setup.py install`, for that matter. For first timers, having a newer release and maybe a conda package would be great. My students will be grateful :)

**Comment by DMTSource** [comment]
Need a new release and hopefully an updated pip! Would be great as taking from live master is pretty scary without tests. Being used in Quant Connect cloud platform for algorithmic trading but had to resort to very old pip version :(

**Comment by fmder** [comment]
I did it! 1.2.0 is out.
