### ISSUE TITLE
unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by pranavdheram** [DEAP/deap#198]
toolbox.register("mate",tools.cxSimulatedBinaryBounded, low=BOUND_LOW, up=BOUND_UP,eta=20.0)
    toolbox.register("mutate", tools.mutPolynomialBounded, low=BOUND_LOW, up=BOUND_UP, eta=20.0, indpb=1.0/N_Stocks)
    toolbox.register("select", tools.selNSGA2)
    toolbox.register("evaluate", evaluate_individual)
pop = toolbox.population(10)

These are my settings. From here, I run the aglorithm as given in the DEAP documentation. 
But I am getting an error, 'unsupported operand type(s) for /: 'NoneType' and 'float'

![image](https://cloud.githubusercontent.com/assets/14910014/25844942/af8344e2-34c9-11e7-8335-b80286f4c8d1.png)

Please check the https: link for a screenshot of the error it is throwing. 
Any help will be greatly appreciated. Thank you.

**Comment by fmder** [comment]
It looks like your individuals haven't been evaluated.

**Comment by pranavdheram** [comment]
@fmder It seems to throw an error well before it evaluates any individual. There seems to be something wrong with the selection operator I'm using. Could that be a problem? But the example in DEAP documentation does the same thing. 
Just to check, I used 
toolbox.register("select", tools.selTournament, tournsize=3) 
instead of  _selNSGA2_ and it worked fine. 

Am I not passing the arguments required by NSGA2 correctly? Thanks. 
PS: Same issue with SPEA2 also.

**Comment by fmder** [comment]
You should evaluate your individual before any selection can​ occur.

**Comment by pranavdheram** [comment]
Theoretically, yes. evaluation before selection. But what I am concerned about is that when using a different selection operator, why does it work?  Thanks for the prompt reply.
