### ISSUE TITLE
Make Requirements section clearer

### ISSUE THREAD

**Issue by bladeoflight16** [DEAP/deap#201]
Before I read on, I thought that DEAP *only* ran on Python 2.6. I'm glad I read on, but it would be nice if the Requirements were a little more explicit to begin with. Here's a suggested change, if you find it useful to get started:

> The most basic features of DEAP require Python 2.6 or higher. In order to combine the toolbox and the multiprocessing module, Python 2.7 or higher is needed for its support to pickle partial functions. CMA-ES requires Numpy, and we recommend matplotlib for visualization of results as it is fully compatible with DEAP's API.
>
> DEAP is compatible out of the box with Python 3 since version 0.8. The installation procedure automatically translates the source to Python 3 with 2to3.

Also corrected some minor grammar/mechanics issues. "Requires" should be "require" since "features" is plural. There should be a comma before Python 2.7. I added spaces between Python and the version numbers since that's how they're normally written.

If you're not supporting all versions of Python 3, you'll want to make it explicit which versions or minimum versions you're supporting. This is a pretty common requirement. E.g.,

> The most basic features of DEAP requires Python2.6, Python2.7, or Python 3.3 or higher.

**Comment by fmder** [comment]
This is fixed in 0092b30
