### ISSUE TITLE
about tools.selBest and tools.selWorst

### ISSUE THREAD

**Issue by Gab0** [DEAP/deap#207]
After reading issues here, I discovered the real workings of tools.selBest and tools.selWorst. But it took some time and pain to finally discover this (kinda newb).
So the behavior of selecting individuals based only on the first fitness value -  then the next if a tie break is needed... is intended. 
Of course we can write our own selection tools, but can someone explain me why the current behavior is better (or perhaps more generic) than using the sum of all the fitnesses, multiplied by respective weights, as the ranking criteria? 
That's a simple evaluation, yet complete, and more intuitive. Or could be made as new functions.. to show the average newb more options right away.
This 'rant' is here because, currently, those functions names are somewhat misleading 🌜 
Best regards..

**Comment by fmder** [comment]
This kind of reduction would be really unstable for mixed minimization and maximization. Moreover, the lexicographic behaviour is somewhat the standard in the literature, at least when I was up to date.
