### ISSUE TITLE
Maximization isted of minimization

### ISSUE THREAD

**Issue by GrzegorzGiniewicz** [DEAP/deap#211]
Hi.

i have problem with minimization of ackley benchmark function. I cant achieve minimization.

im using  

creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, typecode='d', fitness=creator.FitnessMin)

Im loking for help on stackoveflow. There is my code. Link:

https://stackoverflow.com/questions/44576799/minimize-a-function-using-deap

**Comment by fmder** [comment]
You must use axis=0 when registering numpy stats operators. It should get you a better insight. Otherwise, your code look fine to me and there is no bug on that aspect in DEAP.

**Comment by GrzegorzGiniewicz** [comment]
I used axis = 0 but it doesn't help. I need to use SelRoulette for my program but it still going for maximization, no matter if i put in weights 1.0 or -1.0 or use FitnessMin or FitnessMax. When i use SelTournament, tournsize = 3 i can change weights and it's maximization for 1.0 and minimization for -1.0.  Why it doesnt work with SelRoulette ? What can i do to achive minimization and use SelRoulette?

**Comment by fmder** [comment]
Ho yeah, roulette selection cannot be used for minimizing has it cannot
handle negative numbers.

Le 17 juin 2017 07:07, "GrzegorzGiniewicz" <notifications@github.com> a
écrit :

**Comment by GrzegorzGiniewicz** [comment]
Thanks, for quick answer and sorry for trouble.

**Comment by fmder** [comment]
Maybe you can try #87, if it works you could propose a pull request.

**Comment by GrzegorzGiniewicz** [comment]
I've changed selection for SelBest but i cant set k= 20 [like this: (toolbox.register("select", tools.selBest, k=20) ] im geting error: "selBest" got multiple values for keyword argument 'k'. And still its maximizing, even with :
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, typecode='d', fitness=creator.FitnessMin)

I understand that k is for the number of individuals to select.
Without k parametr in selection it works but still maximizing.


import random
import numpy
from deap import algorithms
from deap import base
from deap import creator
from deap import tools
from deap import benchmarks
from random import Random
from time import time
import math

toolbox = base.Toolbox()  
ind = 5
IND_SIZE = ind

creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, typecode='d', fitness=creator.FitnessMin)

toolbox.register("expr", random.sample, range(IND_SIZE), IND_SIZE,)

toolbox.register("individual", tools.initIterate, creator.Individual, toolbox.expr)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutGaussian, mu=0.2, sigma=0.2, indpb=0.1)
toolbox.register("select", tools.selBest)  #k parameter doesnt work
toolbox.register("evaluate", benchmarks.ackley)


def main():
prng=None
best=None

if prng is None:
    prng = Random()
    prng.seed(time())

random.seed(prng)
pop = toolbox.population(n=100)

stats = tools.Statistics(lambda ind: ind.fitness.values)
stats.register("best", numpy.mean, axis=0)

algorithms.eaSimple(pop, toolbox, 0.9, 0.2, 100, stats=stats)

return pop, best

pop,best= main()

**Comment by fmder** [comment]
In eaSimple, selection is made to replace the whole population with ``k=len(population)``.

**Comment by fmder** [comment]
If you want to customize selection with multiple operators I'd say you should copy the content of eaSimple in your own script and replace the selection part, you'll be able to get exactly what you want really easily. The content of eaSimple is no more than 30 lines of code.

**Comment by GrzegorzGiniewicz** [comment]
ok i changed k for 20 but still it's maximizing. How i can achive minimization ?

**Comment by fmder** [comment]
How do you see that it is maximizing?

**Comment by GrzegorzGiniewicz** [comment]
im printing results :
https://pastebin.com/XmSeegsV

**Comment by fmder** [comment]
I just tested your script. I just saw that the "best" you are printing is the average of all fitnesses. What you really should look for is the min value. Add those lines to your script

```python
stats.register("min", numpy.min, axis=0)
stats.register("max", numpy.max, axis=0)
stats.register("avg", numpy.average, axis=0)
```

You'll see that the min value starts around 7 or so and goes to 0 in about 5 to 10 generations. Why does it go up again? It is because of the And variation operator and your high crossover and mutation rate. The evaluation is done after variation and before selection thus you might modify the best individuals. However by using a hall of fame you will still capture it.

With high crossover rate it is possible for the max value to go up and the min value to go down averaging the optimisation result over the entire population, exactly what you are observing. Essentially you should just check for the min value.

**Comment by GrzegorzGiniewicz** [comment]
Thank you very much for help and patiance.

**Comment by fmder** [comment]
:)

2017-06-17 10:07 GMT-04:00 GrzegorzGiniewicz <notifications@github.com>:
