### ISSUE TITLE
In python DEAP package, why this function can be called from a module which dose not have such function?

### ISSUE THREAD

**Issue by zdeng868789** [DEAP/deap#212]
I have just started to use the DEAP package in python. Following the tutorial, I can't understand this statement:

`toolbox.register("cross",tools.cxTwoPoint)`

I understand that tools.cxTwoPoint is to call the `cxTwoPoint` function. However, I checked the source code, the `cxTwoPoint` function is not within tools module, and it is a defined function within `mutation.py`. Also, I did't find any statement in `tools.py` which may relate to `mutation.py` or `cxTwoPoint`.

Can someone help me? Many many thanks!!!

**Comment by fmder** [comment]
https://github.com/DEAP/deap/blob/master/deap/tools/__init__.py#L24

then

https://github.com/DEAP/deap/blob/master/deap/tools/crossover.py#L30

2017-06-16 12:25 GMT-04:00 zdeng868789 <notifications@github.com>:

**Comment by zdeng868789** [comment]
Thanks. I thought the `tools.py` is using this module: 

https://github.com/DEAP/deap/blob/master/deap/benchmarks/tools.py. 

May I ask what is it for?

**Comment by fmder** [comment]
They are for benchmarking your algorithms.
