### ISSUE TITLE
selTournament - how does it work?

### ISSUE THREAD

**Issue by drozzy** [DEAP/deap#214]
For the [selTournament](http://deap.readthedocs.io/en/master/api/tools.html#deap.tools.selTournament) doc says:

> deap.tools.selTournament(individuals, k, tournsize, fit_attr='fitness')
> Select _k_ individuals from the input individuals using _k_ tournaments of tournsize individuals. The list returned contains references to the input individuals.

Why is it selecting using "k" tournaments? Isn't the "tournsize" parameter there precisely to determine the number of tournaments?

Perhaps it should say this?

> Select _k_ individuals from the input individuals using tournaments of _tournsize_ individuals. The list returned contains references to the input individuals.

**Comment by fmder** [comment]
Each of the *k* tournaments is made of *tournsize* individuals. This means,
if k is 10 and tournsize is 3, 3 individuals are selected randomly from
your population and the best one is selected. This process is repeated 10
times.

Cheers,

Le 24 juin 2017 5:48 PM, "Andriy Drozdyuk" <notifications@github.com> a
écrit :

**Comment by drozzy** [comment]
Oh! Got it.

What about this (just like you said):

> `tournsize` individuals are selected randomly from your population and the best one is selected. The process is repeated `k` times.

**Comment by fmder** [comment]
That is more clear.

Le 25 juin 2017 12:16, "Andriy Drozdyuk" <notifications@github.com> a
écrit :

**Comment by dwightee** [comment]
I would like to have an additional question to this. I thought selTournament is only selecting individuals for crossover. But when I use eaSimple with 0 probability of crossover and no select defined (commented out)

```
### toolbox.register("select", tools.selTournament, tournsize=5)
algorithms.eaSimple(pop, toolbox, 0, self.mut_prob, self.gen_count, halloffame=hof,)

```
I get an error  " toolbox object has no attribute select". My question is how exactly does DEAP use the winners of the tournaments?

**Comment by fmder** [comment]
eaSimple, eaMuPlusLambda and eaMuCommaLambda requires the select function to be defined in the toolbox.

In eaSimple "select" selects the individuals for the next generation, mating and mutating is done at random.

That is why we encourage you to write your own main loop and not use the algorithm functions. You will be absolutely certain about what is called and when.
