### ISSUE TITLE
module 'deap.tools' has no attribute 'DeltaPenalty'

### ISSUE THREAD

**Issue by sunils27** [DEAP/deap#217]
I installed deap with pip install. However I am unable to include constraint handling because it is unable to find DeltaPenalty in the tools module. 

I get the following error:
module 'deap.tools' has no attribute 'DeltaPenalty'

Any ideas on how to fix this?
Thanks!

**Comment by fmder** [comment]
You have to install the GitHub master ti get the constraints.

**Comment by sunils27** [comment]
Thanks
