### ISSUE TITLE
genetic programming add function with parameters

### ISSUE THREAD

**Issue by JayDeng2837** [DEAP/deap#218]
Hi,

I was trying to optimize a set of operators on a given data set, while the operators themselves have parameters that needs to be optimized as well.

That being said,  The task is to first generate a bunch of trees of operators. Second, for each tree,  it is a traditional genetic algorithm optimization problem where inputs are floats/ints.

Is there a neat way to achieve this goal using deap? or is there a tutorial already on this topic that i am not aware of? thanks.

**Comment by wangsy15** [comment]
Have you solved it yet?

**Comment by wangsy15** [comment]
Have you solved it yet?
