### ISSUE TITLE
Issue in mutation function

### ISSUE THREAD

**Issue by EnricoBeltramo** [DEAP/deap#225]
Hello,
I had a issue with mutation function. I created a project very similar to onemax.py with individuals composed by different fields float and integer with a specific range. But, when I call the function toolbox.mutate(), it return a new individual with a element different from previous specified range: the field was defined as integer with range 24-96 and it's changed to 0. Is it correct? Did I miss something?

Greets,

**Comment by fmder** [comment]
Most mutations are agnostic of the range. The only mutations that will keep the valid range are those accepting arguments low and up.

**Comment by orena1** [comment]
@fmder how do you suggest to create mutations which are from the correct range/type?
