### ISSUE TITLE
Question on difference in code in example onemax.py

### ISSUE THREAD

**Issue by acmelhorn** [DEAP/deap#231]
This may be a stupid question/easy answer (new to deap and python), but when going over the onemax.py code [https://github.com/DEAP/deap/blob/2c4f926e2a51c9ec96efec117910ce6c47d15ab5/examples/ga/onemax.py]

I saw the same command was written in two ways:

- line 88:  ` fitnesses = list(map(toolbox.evaluate, pop))`
- line 132:  `fitnesses = map(toolbox.evaluate, invalid_ind)`

According to the python support `map()` returns a list.  Is there a reason the `list()` command is needed in line 88?  If so, why is it not needed in line 132?  Or is this a typo/unneeded?

Thanks!

**Comment by fmder** [comment]
This is due to 2to3 conversion. In Python3 map returns a generator. If the fitness are iterated multiple times list(map(...)) must be used.

**Comment by acmelhorn** [comment]
Wouldn't `list()` need to be used for the while statement then too?  Or am I missing something?

**Comment by fmder** [comment]
It only depends if the variable is used more than once.

**Comment by acmelhorn** [comment]
The variable `fitnesses` is first defined on line 88, but then defined _n_ times on line 132 as it is in the main while loop of the GA.  `fitnesses` is then iterated through once before it is redefined from either line.  In both instances it seems that the return from `map()` would need to be a list or generator, not different for each of the two lines/calls.  I am not sure which would be best, but it appears to me that they should be the same though, as `fitnesses` is used in the same way.

Again, sorry I am new to this.  I realize this may now be out of scope of this board, any pointers would be appreciated though :)

**Comment by fmder** [comment]
Since fitnesses is never twice in loop iteration this is ok. A new generator is created every iteration. On line 88 the list could be removed. As I said it is probably just an artifact of the 2to3 automatic translation between Python2 and Python3

**Comment by acmelhorn** [comment]
Sorry I misunderstood you.  I didn't realize you were referring to an automated translation.  Makes more sense now, why the one would have `list()` and the other not.  Thank you!
