### ISSUE TITLE
Issue with Constraints Handling functions

### ISSUE THREAD

**Issue by gabriolu** [DEAP/deap#233]
When I try to run the code:

`import random

from deap import base
from deap import creator
from deap import tools

penalty = 10

creator.create("Fitness", base.Fitness, weights=(1.0,-1.0))
creator.create("Individual", list, fitness=creator.Fitness)

toolbox = base.Toolbox()

toolbox.register("attr_bool", random.randint, 0, 1)

toolbox.register("individual", tools.initRepeat, creator.Individual, 
    toolbox.attr_bool, 20)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

def evalMO(individual):
    
    half = individual[:len(individual)/2]  
    
    return sum(individual), sum(half)
    
def feasible(individual):
    
    if sum(individual)<90:
        return True
    return False
    
def distance(individual):
    """A distance function to the feasibility region."""
    return sum(individual)-90

toolbox.register("evaluate", evalMO)
toolbox.decorate("evaluate", tools.DeltaPenality(feasible, 10, distance))
toolbox.register("mate", tools.cxUniform, indpb=0.5)
toolbox.register("mutate", tools.mutUniformInt, low=0, up=1, indpb=0.05)
toolbox.register("select", tools.selNSGA2)`
I got the error 

>  AttributeError: 'module' object has no attribute 'DeltaPenality'

Why is that?

**Comment by yudai-nkt** [comment]
I don't test your code, but I think you wanted to use `DeltaPenalty`, not `DeltaPenality`.

**Comment by gabriolu** [comment]
I tried both spellings but I get the same error

**Comment by fmder** [comment]
You have to install the master from GitHub. We are yet to do a release.

**Comment by gabriolu** [comment]
Thanks for clarifying

2017-10-10 7:12 GMT-04:00 François-Michel De Rainville <
notifications@github.com>:

> You have to install the master from GitHub. We are yet to do a release.
>
