### ISSUE TITLE
nsga2.py example cannot import name 'hypervolume'

### ISSUE THREAD

**Issue by zwelz3** [DEAP/deap#238]
In python 3 environment:
`pip install deap
`

From examples folder:
`python nsga2.py
`

> Traceback (most recent call last):
  File "nsga.py", line 25, in <module>
    from deap.benchmarks.tools import diversity, convergence, hypervolume
ImportError: cannot import name 'hypervolume'

Upon inspection of installed file /deap/benchmarks/tools.py, the method hypervolume is missing. I think this has to do with requiring the flag _build_ext_ during build, but I'm not sure. Issue appears to be resolved by simply adding the hypervolume method from the git source into the installed tools.py file.

**Comment by fmder** [comment]
Have you installed the master version? I'm not sure it has been officially released yet.

**Comment by zwelz3** [comment]
Hmm that is probably the issue. Interesting as I found the same issue on a google thread from 2 years ago. Not sure when it will be rolled it into the official release.

**Comment by fmder** [comment]
Its been a few years now that we are due for a release.
