### ISSUE TITLE
test_creator tests don't actually run

### ISSUE THREAD

**Issue by dmrd** [DEAP/deap#252]
Hello,

I noticed that [the test creator](https://github.com/DEAP/deap/blob/master/deap/tests/test_creator.py) test doesn't seem to actually have a main method to invoke the tests.  This is in comparison to other tests such as [the test logbook](https://github.com/DEAP/deap/blob/a1412d71b50606a7e4e87c3ba538b25603b84266/deap/tests/test_logbook.py#L41) file.

Am I missing something here?

-David

**Comment by fmder** [comment]
Tests are run by nosetests.

**Comment by dmrd** [comment]
Got it. Thanks for quick response!
