### ISSUE TITLE
Customised Function

### ISSUE THREAD

**Issue by xuyaoGitHub** [DEAP/deap#253]
How to avoid meaningless subtree eg. sub(x1, x1)?
And how to enforce one param to be constant eg. add_constant(x1, constant)?

Thanks in advance

**Comment by fmder** [comment]
For your first question, this is a currently active research topic :)
As for your second question you could try Strongly Typed GP.

The github issues are for bug, the mailing list would be a better place to have this kind of discussion.
https://groups.google.com/forum/#!forum/deap-users
