### ISSUE TITLE
Integers representation of  chromosomes

### ISSUE THREAD

**Issue by DeepWolf90** [DEAP/deap#254]
let's say i have a chromosome with three integers gene as shown in the following code

    toolbox.register("attr_int1", random.randint, 3, 5)
    toolbox.register("attr_int2", random.randint, 1, 10)
    toolbox.register("attr_int3", random.randint, 10, 15)
    toolbox.register("individual", tools.initCycle, creator.Individual,
             (toolbox.attr_int1, toolbox.attr_int2, toolbox.attr_int3),
              n=1)

what is the best crossover and mutation for integers genes?

**Comment by fmder** [comment]
What is the best is kind of an open question... Those that can work with integers though are cxOnePoint, cxTwoPoint, cxUniform and mutUniformInt
