### ISSUE TITLE
TypeError: Both weights and assigned values must be a sequence of numbers when assigning to values of <class 'deap.creator.FitnessMax'>

### ISSUE THREAD

**Issue by lemo2012** [DEAP/deap#256]
Traceback (most recent call last):
  File "oneMax.py", line 58, in <module>
    pop, log, hof = main()
  File "oneMax.py", line 53, in main
    pop, logbook = algorithms.eaSimple(pop, toolbox, cxpb=0.5, mutpb=0.2, ngen=10, stats=stats, halloffame=hof, verbose=True)
  File "/usr/local/lib/python3.6/site-packages/deap/algorithms.py", line 152, in eaSimple
    ind.fitness.values = fit
  File "/usr/local/lib/python3.6/site-packages/deap/base.py", line 193, in setValues
    self.weights)).with_traceback(traceback)
  File "/usr/local/lib/python3.6/site-packages/deap/base.py", line 185, in setValues
    self.wvalues = tuple(map(mul, values, self.weights))
TypeError: Both weights and assigned values must be a sequence of numbers when assigning to values of <class 'deap.creator.FitnessMax'>. Currently assigning value(s) 4 of <class 'int'> to a fitness with weights (1.0,).

**Comment by fmder** [comment]
Your evaluation should return a tuple of one element.

**Comment by fmder** [comment]
Just tested it and it works, *nicely*.

**Comment by joseortiz3** [comment]
The usage of single-element tuples makes reading confusing. Consider using lists instead.

```python
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
# the goal ('fitness') function to be maximized
def evalOneMax(individual):
    return sum(individual),
```
vs
```
creator.create("FitnessMax", base.Fitness, weights=[1.0])
# the goal ('fitness') function to be maximized
def evalOneMax(individual):
    return [sum(individual)]
```

**Comment by Henry0191** [comment]
@fmder no, it's not working at all. I'm getting the same error. With @joseortiz3 changes it works...

**Comment by adrianosantospb** [comment]
Hi, all.

It's simple. Check if in your code your function has function + ,  like this:

def evalOneMax(individual):
    return sum(individual),   #<---- comma

**Comment by jakehoskins** [comment]
> Hi, all.
> 
> It's simple. Check if in your code your function has function + , like this:
> 
> def evalOneMax(individual):
> return sum(individual), #<---- comma

This was the missing ticket for me. Looks like there's a typo in the Jupyter notebook and readme.

**Comment by ericklarac** [comment]
I was facing the same issue but adding the comma solved it.

**Comment by joseortiz3** [comment]
If the output of the function needs to be a tuple, a decorator should be written and employed to coerce the values passed around appropriately. 

Relying on people to include a comma when all they want to do is return a single value leads to these issues.

**Comment by fmder** [comment]
@joseortiz3 There is a story in the backlog about accepting scalar values in fitnesses.

**Comment by joseortiz3** [comment]
@fmder To be more precise, what I mean is
```python
@coerce_tuple_arguments(arg_indices=[1])
def some_function(argument1: tuple, .......):
    assert isinstance(argument1, tuple)
```
Which could then be called with `some_function(1.0)` and the decorator would convert `1.0` to `(1.0,)`. Is this not better?

**Comment by robertbarac** [comment]
The solution is simple. When we create the fitness function or the objective function, we have to put a comma (,) when we return the number, in any case of returning. I'm running some code making my first steps with deap, reading a book, but we do not copied the comma that was typed in the code of the book.
