### ISSUE TITLE
NSGA-2 evaluates individuals more than one time

### ISSUE THREAD

**Issue by SvennoNito** [DEAP/deap#258]
Hey,
I'm working with your [example NSGA-2 script](https://github.com/DEAP/deap/blob/master/examples/ga/nsga2.py). I noticed that there might be an error with the following lines of code:

```
        for ind1, ind2 in zip(offspring[::2], offspring[1::2]):
            if random.random() <= CXPB:
                toolbox.mate(ind1, ind2)
            
            toolbox.mutate(ind1)
            toolbox.mutate(ind2)
            del ind1.fitness.values, ind2.fitness.values
        
        # Evaluate the individuals with an invalid fitness
        invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
        fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
        for ind, fit in zip(invalid_ind, fitnesses):
            ind.fitness.values = fit
```

The purpose seems to be to NOT evaluate an individual, if it has already been evaluated before (smart!). But here, `del ind1.fitness.values, ind2.fitness.values` will always be executed, no matter whether crossover and mutation took place or not. Shouldn't it be the case, that this field is only deleted if either mutation or crossover took place?

Best,
Sven

**Comment by fmder** [comment]
The code has probably been scavenged from multiple other examples. In its original version NSGA-2 mutates all individuals, thus all individuals need to be reevaluated. In other examples, not all fitnesses will be deleted and this part will actually do something.
