### ISSUE TITLE
Custom type for custom representation of a chromosome

### ISSUE THREAD

**Issue by aziz86** [DEAP/deap#260]
Hi,
I am quite interested in your framework and would love to use it. However, I am kind of confused by the types offered for different kinds of representations.
I have a custom and problem specific representation that has to be made and I am wondering whether you could shed some light on my concern.
Well, my chromosome is in this form : 
The locus are : (v1, v2), (v2, v3), (v3, v4) 
The alleles are : (a,b), (b,c), (c,d)
Think of it as a mapping.
I am not sure which is the best type to be used in order to represent the aforementioned individual.
Any suggestion ?
Thanks in advance,

**Comment by fmder** [comment]
I think I'm late here, but if it is a direct mapping, you could directly
work with you tuple of tuples (or single chained list) representation and
translate in the evaluation. From your example, the intermediate
representation does not add any information and seems to be only for
evaluation purpose.

Regards,

2018-03-06 21:45 GMT-05:00 src_src <notifications@github.com>:
