### ISSUE TITLE
Difference tools.DeltaPenalty vs tools.DeltaPenality

### ISSUE THREAD

**Issue by SvennoNito** [DEAP/deap#263]
Hey, I'm currently trying to implement a constraint function and came accross the following issue. [Here](http://deap.readthedocs.io/en/master/tutorials/advanced/constraints.html) I found `tools.DeltaPenalty(feasible, 7.0, distance)` function, whereas [here](http://deap.gel.ulaval.ca/doc/dev/tutorials/advanced/constraints.html) I found `tools.DeltaPenality(feasible, 7.0, distance)`. Notice the "i" in penality. 

I'm a bit confused. They seem to do the same, is it a spelling error? Or do they actually do different things?

**Comment by fmder** [comment]
It was a typo due to my mother language. In french we say "pénalité" which sounds much like penality, but the english orthographe is penalty. We created an alias from penality to penalty. They are the same function.
