### ISSUE TITLE
solve shortest path problem 

### ISSUE THREAD

**Issue by Yuminzhou** [DEAP/deap#269]
Hi,

I am very new to DEAP, but I am researching on shortest path problem with multi mode transportation. I have designed a network. each node might link to multiple nodes, and for each link, might have multiple edges. It looks like a transportation network. From different city, there are multiple transportation mode. For example, from LA to SF, we can take plane, train and drive a car. For my problem, I will decide the start point (Node 1) and end point (Node 2). I am considering to design the input data using edge number. one induvidual should looks like [1,0,0,1,0,0,0,0,1,0,0] means: the route should be node 1 --> node 3 --> node 5 --> node 6, and the edge is edge 1 --> edge 4 --> edge 9

But I don't know how to program using DEAP package, do you have any suggestions or tutorial/example for reference? Thank you.

**Comment by fmder** [comment]
This looks like a version of the Traveling Salesman Problem. You can look at ``examples/ga/tsp.py``.

The issues are reserved for bugs. For help you can ask on the deap-users mailing list.
