### ISSUE TITLE
deap number of processes

### ISSUE THREAD

**Issue by betterze** [DEAP/deap#270]
I use deap 1.2.2 on window 10 anaconda python 3.6. When I run my code without multiprocessing, it use all  processors with a cpu utilization 55% (it use all processors instead of fully using several processors.). When I use 'pool = multiprocessing.Pool(processes=2)', it use all processors and reach 100% cpu. But my laptop has 4 cores and 8 logical processors. Is this because Deap Package itself use parallel computing implicitly?

And the code not matter with or without multiprocessing, it run much faster in my laptop than in server, but the server have stronger cup and more processors. Could you help me understand why this happen?

**Comment by fmder** [comment]
There are many reasons why it may run faster on some computer. The first reason that comes to mind,  I think Anaconda have MKL optimized numpy/scipy libraries. Or maybe someone else is running code simultaneously on the server.

I saw that context switching can create imprecision in windows cpu utilisation. See this for example: https://stackoverflow.com/questions/35791068/why-single-python-processs-cpu-usage-can-be-more-than-100-percent/43597432

DEAP does not have any multiprocessing that users are not aware of (enabled by using toolbox.map for example).

I will close this as this is not really an issue. Fell free to continue ask questions.

**Comment by betterze** [comment]
Thank you for your reply. I search MKL related things for several days, I still could not solve it. One moth ago, I didn't not use multiprocessing, i could run around 10 deap program at the same time., every program takes 5% cpu But now, one program takes 55% cpu (without multiprocessing). I can not repetite the result i did before (every program take 5% cpu) even the code is the same. Do you know why this happen
