### ISSUE TITLE
Early Stopping eaMuPlusLambda

### ISSUE THREAD

**Issue by jonathanglima** [DEAP/deap#271]
In order to optimize performance and use deap in production I created a custom eaMuPlusLambda that gets the best fitness individual (with an external function, due to my own business criterions and weights) and if my best fitness individual is the same in n generations, I stop the algorithm.

I know it's a simple early stopping but I just wanted to know if this feature is welcome and if it is, what's the best way to add it (another eaMuPlusLambda function, modify eaMuPlusLambda to add new threshold and best fitness individual function or any other ideas).

**Comment by fmder** [comment]
As we see it, algorithms should become generators in 2.0 making it much easier to add custom stopping criterion.
