### ISSUE TITLE
Publish logos as svg

### ISSUE THREAD

**Issue by aut0** [DEAP/deap#272]
Hi,

I was wondering if you could publish your logos as svg as well. I only found the png. Maybe also your github profile picture as it is a bit smaller than the full big logo. It would be helpful for making figures.

Thanks

**Comment by fmder** [comment]
I added to the repository
https://github.com/DEAP/deap/blob/master/doc/_static/DEAP.pdf

**Comment by aut0** [comment]
Thanks! That was quick.
