### ISSUE TITLE
Fitness function in external binary possible?

### ISSUE THREAD

**Issue by kramer65** [DEAP/deap#273]
A few years back I worked with deap (and really enjoyed it). Now I'm up for a new project in which I need to use Evolution Strategies. The fitness function is very computational intensive though, and is therefore built in Golang. 

I thought of either calling it using `eval()` OR using a message lib like zeromq to transfer the fitness arguments and results back to my deap code in Python.

So I wonder; is there anything agains using this external golang variable as a fitness function? Are there things I should watch specifically?

**Comment by fmder** [comment]
No. Most of my evaluation functions are in C.
