### ISSUE TITLE
alling back to the python version of hypervolume module. Expect this to be very slow.

### ISSUE THREAD

**Issue by akselthele** [DEAP/deap#275]
Warning (from warnings module):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\deap\tools\_hypervolume\pyhv.py", line 33
    "module. Expect this to be very slow.", ImportWarning)
ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.

please assist with the warning  above

**Comment by fmder** [comment]
Duplicate #244
