### ISSUE TITLE
some `list`s are redundant and there is a typo

### ISSUE THREAD

**Issue by Freakwill** [DEAP/deap#278]
I have read the source codes. and I see the following codes. I think it is not different from 
`population = offspring`. Yes?

       # Replace the current population by the offspring
        population[:] = offspring

**Comment by Freakwill** [comment]
But I believe something is really redundant, such as `list` in
`for a, b in list(d.itmes()):` and `max(list(map(f, list(...))))` at least in `algorithms.py`
that may make the algorithm slow down. I consider to submit a RP

**Comment by fmder** [comment]
I don't see the repported max(list(map(...))) nor for a, b in list(d.items()) anywhere in the code. I guess your are looking at your 2to3ed version. The issue should be to translate officially DEAP to Python 3.
