### ISSUE TITLE
Example in documentation Overview does not work in Python 3

### ISSUE THREAD

**Issue by petrposik** [DEAP/deap#284]
Being new to deap, I go through the documentation. On Overview page, I took all the code and copied it to a Python script. When I run it using Python 3 (3.6), I get the error

```
Traceback (most recent call last):
  File "ex1.py", line 69, in <module>
    pop = main()
  File "ex1.py", line 47, in main
    for child1, child2 in zip(offspring[::2], offspring[1::2]):
TypeError: 'map' object is not subscriptable
```

This is caused by `offspring` being created as a result of `map()` which returns in iterator in Python 3, as opposed to a list returned by Python 2. 

Since this is the first example of using DEAP, I guess it should work in Python 3.

Simply using `list(map(...))` instead of `map(...)` helps, but it is IMHO not the right solution because it presumes that the offspring population is a list of individuals which does not have to be always true.

**Comment by fmder** [comment]
I think the proposed solution is the good one. The offspring are most generaly a list and this is enforced not by the list you add but by the map itself which returns a 'linear' iterable. In case the population would be say a matrix, some more code would be needed in both python 2 and 3.

I will close this as the current version of DEAP (1.2) is still coded in python 2 and we use 2to3 for translation. DEAP 2.0 will be python 3.
