### ISSUE TITLE
How to use history_index ?

### ISSUE THREAD

**Issue by FlyingPumba** [DEAP/deap#296]
I'm looking into using the [History class](https://deap.readthedocs.io/en/master/api/tools.html#history). According to the documentation:
> The index present in their history_index attribute will be used to locate their parents, it is then modified to a unique one to keep track of those new individuals. This method should be called on the individuals after each variation.

But I don't know which value should I choose as `history_index`  for each new individual after crossover.
Is there any example of this ?

**Comment by fmder** [comment]
The history index is automatically added if you decorate your crossover and mutation with 

```python
# Decorate the variation operators
toolbox.decorate("mate", history.decorator)
toolbox.decorate("mutate", history.decorator)
```

This is the only code you need to add to get the history working.

I will close this issue as this kind of discussion is better targeted on the mailing list : http://groups.google.com/group/deap-users
