### ISSUE TITLE
The cTools module is not available anymore?

### ISSUE THREAD

**Issue by yyuekirin** [DEAP/deap#307]
Dear Deap team,
From the link below, there is a cTools module that using the C++ version of the NSGA II algorithm.
But it seems that cTools is not available anymore now?
Cannot find the cTools code in the latest version of DEAP.
Thanks
https://deap.readthedocs.io/en/0.9.2/tutorials/speedup.html

**Comment by fmder** [comment]
Sorry for the big delay I will answer this one for posterity.

cTools have been dropped since it was a mess to have the exact same implementation of NSGA-II in python and C. We decided that it was better to have a solid state of the art implementation than the few seconds gain that C was providing.
