### ISSUE TITLE
logo missing on top left corner of docs page

### ISSUE THREAD

**Issue by bionicles** [DEAP/deap#325]
hi, there is an issue with the documentation page:

![deap-logo-missing-screenshot from 2019-01-15 14-28-07](https://user-images.githubusercontent.com/24532336/51204609-f938ee00-18d1-11e9-8585-5ff536143567.png)

**Comment by cmd-ntrf** [comment]
You are right, and apparently it has been missing for the last five years when we still using Mercurial. Weird.

Commit a8e1c9a6ea5a84c51251dbce32b82f80cb6a32af should fix it. 

Thanks for the report!
