### ISSUE TITLE
How weights affect fitness

### ISSUE THREAD

**Issue by adambinch** [DEAP/deap#329]
Hello,

Im using DEAP to optmise robot navigation params in simulation. Im trying to minimise two objective functions. One produces much larger values than the other, yet I want both to be treated equally (im setting the weights to (-1, -1)). 

Will that work, or do I have to manipulate the weights?

Thank you

**Comment by fmder** [comment]
That should do the trick indeed.

**Comment by adambinch** [comment]
Ok thanks. Great software by the way :)
