### ISSUE TITLE
TypeError:Both weights and assigned values must be a sequence of numbers when assigning to values of <class 'deap.creator.FitnessMax'>. Currently assigning value(s) 53 of <class 'int'> to a fitness with weights (1.0,).

### ISSUE THREAD

**Issue by XuanX111** [DEAP/deap#332]
* examples/ga/onemax. line 90 . 

ind.fitness.values = fit
raise error, TypeError:Both weights and assigned values must be a sequence of numbers when assigning to values of <class 'deap.creator.FitnessMax'>. Currently assigning value(s) 53 of <class 'int'> to a fitness with weights (1.0,).

* I changed to ind.fitness.values = [fit] .   It works

**Comment by fmder** [comment]
You probably changed something because the example works fine for me.
