### ISSUE TITLE
Project status, roadmap, 2.0?

### ISSUE THREAD

**Issue by OliverColeman** [DEAP/deap#337]
What's the development status of deap? Is there a roadmap for next releases? Is there a plan or schedule for a 2.0 release? 

The last release was around 1.5 years ago, 1.2.2 in Nov 2017. It looks like there has been some activity in the last few years but that it significantly dropped off a few years ago.

There are some open issues for a [2.0 milestone](https://github.com/DEAP/deap/milestone/3), but these haven't seen any activity for around 8 months to a couple of years.

**Comment by fmder** [comment]
There is a roadmap, but there is no time to achieve it. Most of the development was done while me and @cmd-ntrf were doing graduate studies. Now we are both occupied with tons of other projects.

All contributions are welcomed.

**Comment by yxliang01** [comment]
Hmm @fmder Maybe it's a good idea to release the current master as 1.3.0 or 1.2.3 at least, if you think the current master is stable?

**Comment by fmder** [comment]
I'm working on something that would make 1.3 a real release. Stay tuned.

Le mar. 30 avr. 2019 10 h 52, Xiao Liang <notifications@github.com> a
écrit :

**Comment by yxliang01** [comment]
Then I would suggest release the current master as 1.2.3 :joy: The master contains a bunch of fixes since 1.2.2 as far as I can see. @fmder

**Comment by fmder** [comment]
1.3.0 is out! Check out the new NSGA-III selection!
