### ISSUE TITLE
Solve job-shop scheduling problem

### ISSUE THREAD

**Issue by dzeno** [DEAP/deap#341]
Hi, 

Would it be possible to use DEAP to solve [`job-shop scheduling problem`]( https://en.wikipedia.org/wiki/Job_shop_scheduling)? I've found a few papers using `genetic algorithm` to solve this problem and I would like to try it out. I wonder if it's possible to have a list of jobs with their respective constraints, e.g. dependent tasks, execution times, etc., and fit such input in order to get the best schedule?

The output that I am aiming for is a time-table schedule where all constraints are met for a given set of tasks.

Thanks.

**Comment by fmder** [comment]
This question has already been asked on the mailing list. Yes it should be possible to use deap, with a lot of your code around it to solve your problem. It won't be out of the box.

**Comment by Akhilnandh** [comment]
I m trying to solve a job shop and inventory problem in which I want to represent 2 separate genes,- one for batch size and the other for the number of months of stock. I'd be happy if somebody can tell me how to represent two genes each with individual chromosome representations?
