### ISSUE TITLE
Change SCOOP link

### ISSUE THREAD

**Issue by rahvee** [DEAP/deap#352]
Sadly, SCOOP seems to be have been unmaintained for the last 5 years, and their homepage has been compromised with malware. There's an official end-of-life notification here: https://groups.google.com/forum/#!topic/scoop-users/goklDfcK2N0

You have at least one link to their homepage, prominently displayed in your README. I recommend changing your link from `pyscoop.org`, to either https://scoop.readthedocs.io/en/latest/index.html or https://github.com/soravux/scoop and possibly the end-of-life announcement. Or maybe DEAP can integrate with a different tool for distributed computing?

Thanks

**Comment by fmder** [comment]
8e54d6f fixes the link point to github. As for a SCOOP replacement, its been too loong since I've done multiprocessing other than with the multiprocessing module to says what framework to use.

**Comment by epicfaace** [comment]
@fmder SCOOP still points to the old link at https://deap.readthedocs.io/en/master/ -- have the docs not been deploying?
