### ISSUE TITLE
Hall of fame uses only first fitness value

### ISSUE THREAD

**Issue by rgerkin** [DEAP/deap#368]
When deciding which individuals to add/remove to the hall of fame, only the first element of the fitness is considered.  This stems from the comparison [here](https://github.com/DEAP/deap/blob/master/deap/base.py#L236) where one tuple is compared to another.  Since tuples are compared (for >, >=, <, <=) only by their first element, this means the rest of the weighted values are ignored.  This leads to non-intuitive behavior for the hall of fame, in which individuals that are clearly superior, given the user-specified weights, do not end up included.  The simple fix is to add `sum()` around each side of the inequalities in line 236, and 239.  Line 242 can remain as is since tuple equality comparison gives the expected behavior, and there could be multiple individuals with different composition but the same total fitness.

**Comment by fmder** [comment]
It actually compare them in lexical order. For multi-objective hall of fame, the ParetoFront class should be used.

**Comment by rgerkin** [comment]
@fmder Yes, but one can have a multi-objective problem but be concerned with more than just the non-dominated solutions.  Weights allow the multiple objectives to be pooled into a single objective.  Are you proposing that no version of the hall of fame should consider the weights at all?  

I personally don't find lexical order to be of any value, but assuming it has some purpose, how would you feel about an additional HallOfFame class that uses the summed weighted values (as I originally proposed)?  It would then be an option in addition to the current lexical order HallofFame class and the ParetoFront class.

**Comment by rgerkin** [comment]
@fmder Actually I see now that the problem is deeper.  Only the sign of the weights has any meaning at all in the Fitness comparisons.  A weighted sum would require a different Fitness class that respected the magnitude of the weights.  Is there a reason why this doesn't exist?

**Comment by fmder** [comment]
You can still access the weights of an individual using ind.fitness.weights. This does not exist since we never came across an algorithm that requires it :P. Feel free to contribute :)
