### ISSUE TITLE
convenient way for extension of GA, such as ls-hGA

### ISSUE THREAD

**Issue by Freakwill** [DEAP/deap#391]
Is there some convenient way for extension of GA, such as local search hybrid GA, or some self-adaptive settings. The algorithms in DEAP are designed as functions. That makes things troublesome. If I try to change the probability for mutate or mute adaptively, I have to repeat most code of the algorithms, and add some code to it. Or, run a for-loop whose body is like
```
run algorithm for pop
change probability according to pop, and re-set toolbox
```

It could be designed via OOP as follows. One should only implement the method, while call the variant of GA with the same API, i.e. `__call__`.

```
class GA:
    def __call__(pop, *args, **kwargs):
        pass

class LSHGA(GA):
    def local_search(self, ind):
        # local search algorithm
        return ind

class AdaGA(GA):
    def adapt(self, pop):
        ...

ga = LSHGA()
ga(pop)
```

**Comment by fmder** [comment]
You are perfectly aligned with DEAP 2.0. You should have a look at the iterable-like algorithms (#375). The new exploratory syntax would be

```python
for state in SimpleAlgorithm(pop, toolbox, some_more_args):
    # Make changes to the population somehow
    state.population = new_population

    # Change your toolbox or anything that is in the state
    state.toolbox = my_new_and_awesome_toolbox

    # Compute termination
    if any(ind.fitness.values < (1e-6,) for ind in state.population):
        break
```
