### ISSUE TITLE
Cannot make docs

### ISSUE THREAD

**Issue by loganthomas** [DEAP/deap#400]
I have a few documentation additions that I'd like to submit via a pull request but can't seem to get the docs to build.

![Screen Shot 2019-08-14 at 21 22 29](https://user-images.githubusercontent.com/24984410/63068671-a52ed000-bed9-11e9-9c26-ee9f2500a883.png)

I created a virtual environment with python 3.7.4.

Any suggestions?

**Comment by fmder** [comment]
You need Python 2

Le mer. 14 août 2019 22 h 23, Logan Thomas <notifications@github.com> a
écrit :

**Comment by loganthomas** [comment]
@fmder Thanks, worked like a charm!
