### ISSUE TITLE
Optimizing bounded functions (e.g. Branin)

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [DEAP/deap#416]
Hi 

I'd like to optimize, for example, the so called Branin function defined as the following:

```
def Branin ( x ):
      y = (x[1] - (5.1 / (4 * np.pi ** 2)) * x[0] ** 2 + 5 * x[0] / np.pi - 6) ** 2
      y += 10 * (1 - 1 / (8 * np.pi)) * np.cos(x[0]) + 10
      return y

```
Having a two dimensional input x with the following bounds and a scalar output.
```
bounds = [[-5, 10], 
                 [0, 15]],
```
(first dimension bounded between -5 and 10, while second dimension is bounded between 0 to 15.

I wanted to ask if anyone can share a code snippet for such optimization problem using genetic algorithm or other better algorithms. 

Thanks

**Comment by fmder** [comment]
It is almost exactly one of the provided examples in the examples folder.

**Comment by a-z-e-r-i-l-a** [comment]
> It is almost exactly one of the provided examples in the examples folder.

Hi, could you share a link for it? because I checked the examples in [this link ](https://deap.readthedocs.io/en/master/examples/index.html#)but was rather lost and didn't find something similar.

**Comment by a-z-e-r-i-l-a** [comment]
> It is almost exactly one of the provided examples in the examples folder.
@fmder Hi, could you share a link for it? because I checked the examples in [this link ](https://deap.readthedocs.io/en/master/examples/index.html#)but was rather lost and didn't find something similar.

**Comment by a-z-e-r-i-l-a** [comment]
> It is almost exactly one of the provided examples in the examples folder.


@fmder Hi, could you share a link for it? because I checked the examples in [this link ](https://deap.readthedocs.io/en/master/examples/index.html#)but was rather lost and didn't find something similar.

**Comment by a-z-e-r-i-l-a** [comment]
> It is almost exactly one of the provided examples in the examples folder.

@fmder I checked the examples in [this link ](https://deap.readthedocs.io/en/master/examples/index.html#)but was rather lost and didn't find something similar,  could you please share a link for it?
