### ISSUE TITLE
Question about setting weights for multi-objective fitnesses

### ISSUE THREAD

**Issue by kaoru-okumura** [DEAP/deap#431]
Hello,

I'm learning DEAP for staff scheduling by ga. I'm trying to minimize five objective functions with different importance of each objectives.

I'm setting the weights to (-10.0, -100.0, -1.0, -100.0, -10.0), where I suppose the importance will be higher if the absolute value becomes bigger.
 
Will that work? If it won't, is there any ways to set the importance for multi-objective fitnesses?

**Comment by fmder** [comment]
No it won't. Multi objective will try to optimize all objectives by pushing the Pareto front as far as possible. In the end it is your responsibility to choose the best tradeoff in all non dominated solutions.

**Comment by kaoru-okumura** [comment]
Thank you for your quick response! I understood.
