### ISSUE TITLE
Pool objects cannot be passed between processes or pickled

### ISSUE THREAD

**Issue by discover59** [DEAP/deap#434]
I followed multi processors approach described here. https://deap.readthedocs.io/en/master/tutorials/basic/part4.html

```
import multiprocessing

pool = multiprocessing.Pool()
toolbox.register("map", pool.map)

# Toolbox definition
toolbox.map(toolbox.evaluate, offspring)
```

Above code gets error *Pool objects cannot be passed between processes or pickled.*
But when I used dummy pool it works fine.
```
from multiprocessing.dummy import Pool
```

But latter code uses multithreading. Please let me know what's wrong with multi processors.

**Comment by fmder** [comment]
Is it possible that your individuals cannot be pickled?

**Comment by discover59** [comment]
Since dummy pool works, it's not possible.

**Comment by discover59** [comment]
https://deap.readthedocs.io/en/master/tutorials/basic/part4.html#multiprocessing-module

Is this working for you?

**Comment by fmder** [comment]
Dummy pool is a wrapper around threading, thus it does not pickle.

**Comment by discover59** [comment]
Hmm, did you try using multiprocessing recently?

**Comment by fmder** [comment]
What version of python are you using? I've tested 2.7 and 3.7 and it works just fine.

**Comment by discover59** [comment]
I got this error on 3.6. Will test on 3.7 later and post the result here.

**Comment by fmder** [comment]
I've added multiprocessing tests to the travis agent and they all pass.

https://travis-ci.org/DEAP/deap/builds/657997828?utm_medium=notification&utm_source=github_status

**Comment by dgabriele** [comment]
I'm getting this error on Python 3.8.5 @fmder
