### ISSUE TITLE
Please include Estimation Distribution Algorithm examples

### ISSUE THREAD

**Issue by Soapdemon** [DEAP/deap#443]
Could you please include Estimation Distribution algorithm examples. The mentioned link for examples https://github.com/DEAP/deap/blob/454b4f65a9c944ea2c90b38a75d384cddf524220/examples/eda/fctmin.py

giving 404 error

**Comment by fmder** [comment]
It is in the example folder.

**Comment by Soapdemon** [comment]
> Could you please include Estimation Distribution algorithm examples. The mentioned link for examples https://github.com/DEAP/deap/blob/454b4f65a9c944ea2c90b38a75d384cddf524220/examples/eda/fctmin.py
> 
> giving 404 error



> It is in the example folder.

Thanks
