### ISSUE TITLE
How to get non-linear output？

### ISSUE THREAD

**Issue by wd1969** [DEAP/deap#444]
Sorry to interrupt, I'm debugging nsga3 multi-target evolution, I need to get 200 parameters to weight and remove some unimportant parameters, but I found that the nsga3 output is linear, not obviously distinguish between importance, how to get nonlinear weight output Thank you

**Comment by fmder** [comment]
There is no importance in multi-objective evolution. You will get all pareto optimal trade offs of the combinaison of your parameters.
