### ISSUE TITLE
Possibly Important Bugs of examples/pso/basic.py

### ISSUE THREAD

**Issue by os-popt** [DEAP/deap#446]
In Line 45-48 of [PSO](https://github.com/DEAP/deap/blob/master/examples/pso/basic.py), the ```abs()``` function seems to be used wrongly, as presented below:

```Python
        if abs(speed) < part.smin:
            part.speed[i] = math.copysign(part.smin, speed)
        elif abs(speed) > part.smax:
            part.speed[i] = math.copysign(part.smax, speed)
```

When ```part.smin``` is set to a negative value (e.g., -3), Line 45-46 never be executed. In other worlds, the lower bound checking of speed is not run.

To fix it, maybe delete the ```abs``` function. And also do not need to use the ```math.copysign``` function.

**Comment by fmder** [comment]
Minimum speed should always be positive. The absolute value make it effective both positive and negative, a particle cannot go slower than smin in one direction or the other.

**Comment by os-popt** [comment]
However, according to [this line](https://github.com/DEAP/deap/blob/master/examples/pso/basic.py#L52),  th minimum speed is set to be negative. Note that in PSO, the speed is not the speed **in physic**, it can be negative. We need provide a correct limit for its upper and lower bound. -> @fmder

**Comment by fmder** [comment]
It is not the speed that cannot be negative, it is the exclusion enveloppe that cannot be negative. The speed can be negative (according to the axes) as the sign is conserved.

**Comment by os-popt** [comment]
It seems to be more clear to write Line 45-48 like this:
```
        if speed < part.smin:
            part.speed[i] = part.smin
        elif speed > part.smax:
            part.speed[i] = part.smax
```
I find that many PSO implementations adopt this way for simplicity. And ```abs``` and ```math.copysign``` can be removed for clarity. -> @fmder
