### ISSUE TITLE
Is it possible to extract best individual after every generation?

### ISSUE THREAD

**Issue by SinaAlef** [DEAP/deap#461]
I want to make an animation to demonstrate improving during optimization process. So i need to get best solutions after every generation. How can i do it?

**Comment by DMTSource** [comment]
This may have more luck getting answers on the question board vs reporting as an issue:
https://groups.google.com/forum/#!forum/deap-users

You can copy an algo, like [eaSimple](https://github.com/DEAP/deap/blob/master/deap/algorithms.py#L85), to your script and then in the evo loop add your plotting code, or collect the best ind in pop or the hof[0] at each gen to plot after the evolution.
