### ISSUE TITLE
Integer attributes became floats after some generations

### ISSUE THREAD

**Issue by SinaAlef** [DEAP/deap#462]
In my multi-objective problem my individuals are something like `[int1,int2,flt]`. `int1` is integer in range 0 to 10. `int2` is integer in range 3000 to 4000 and `flt` is a float in range 0 to 1.
I used` cxTwoPoint`, `mutGaussian` and `selNSGA2` as crossover operator,mutation operator and selection operator respectively. After some generations` int1` and `int2` in some individuals became floats which they were supposed to be integers. In some cases they violated my registered upper and lower bounds.
What is best to do in my case ? I know i can use constraints but i want to prevent generation of unwanted types of individuals if it is possible.
Also i want to know if can i use different mutation operators for different types of attributes?

**Comment by fmder** [comment]
You should break down you crossover and mutation in two parts, one acting on the floats and the other on the integers. For the constraints, you can have a look at the Bounded operators.

I will close this as it is not an issue with DEAP per say.
