### ISSUE TITLE
initialize population in vehicle routing problem

### ISSUE THREAD

**Issue by GHARBI-Maamar** [DEAP/deap#466]
Hi everyone
How can I initialize population in vehicle routing problem, the problem is that I want to set in list first item 0 and last item 0 for example [0, 83, 37, 31, 42, 52, 97, 41, 63, 0], I have created a function to do this but the evaluation function indicates an error.

With DEAP i have used this toolbox.register("index", np.random.choice, len(lst), 5, replace=False) to generate my individual but the result give a list like this [91, 98, 87, 83, 66, 70, 77, 63, 38, 92], and the final results after evolution dont give me a tour

**Comment by fmder** [comment]
If you entirely skip the first and last numbers from initialization and add them temporarily in the evaluation function that should do the trick.

As for the toolbox it won't do any magic for you, what you describe is the behaviour of random.choices.
