### ISSUE TITLE
Population size decrease in the example "One Max Problem: Short Version"

### ISSUE THREAD

**Issue by Terahertz0** [DEAP/deap#467]
![image](https://user-images.githubusercontent.com/35922324/77098448-0f34c800-6a1b-11ea-8fe0-184c0b37077c.png)

Why does the population size (nevals I believe) is not constant or close to the initial population size of 300?

Code: https://github.com/DEAP/deap/blob/05518db9d9cfe040cbd8e912ef7a1b3d6e53699b/examples/ga/onemax_short.py

**Comment by cmd-ntrf** [comment]
In this example, a subset of the population is modified at each generation: the probability of an individual being crossed with another is 50%, and mutated is 20%. The algorithm only evaluates the individual that were modified, hence the number of evaluation being systematically inferior to the size of the population except during on generation 0, where no individual has been evaluated in a preceding generation.

**Comment by Terahertz0** [comment]
Is it possible to keep the population size constant or near constant?

**Comment by fmder** [comment]
The population size is always constant, the reported number is only the number of individuals evaluated (with an invalid fitness).
