### ISSUE TITLE
Problem with creating custom Individual

### ISSUE THREAD

**Issue by palkafilip** [DEAP/deap#468]
Hey guys,

I'm working on my own lib for ML. I use your project for genetic optimization. 

I need to create custom type of Individual. I haven't seen any example for that.
For now my individual it's a really simple class with three attributes - parameters, features and fitness, and getter and setter for each field. 

My deap code looks like this:

Create _Individual_ object
```
        creator.create("FitnessMax", base.Fitness, weights=(1.0,))
        creator.create("Individual", Individual, fitness=creator.FitnessMax)
```

Then the idea is to register an _individual_, where we pass some function which tells how to create proper _Individual_ object. It just fills all the attributes with values.

        self.__toolbox.register("individual", individual_constructor, creator.Individual)

and `individual_constructor` in this example is

```
    def create_individual(self, icls):
        icls.parameters = self._create_parameters_part()
        icls.features = self._create_features_part()
        
        return icls
```

I also register population in standard way

        self.__toolbox.register("population", tools.initRepeat, list, self.__toolbox.individual)

And this code works fine, I mean it compiles. But when it comes to create population, whole population consist of same _Individual_ object. For example, if I have population with 100 individuals, they all have same attributies. I debugged `create_individual` function, and it modifies existing _Individual_, instead of creating a new one. I've tried a deep copy mechanism but it also didn't work.

When I modify `create_individual` function to look like this, it works fine:

    def create_individual(self, icls):
        individual = Individual()
        individual.parameters = self._create_parameters_part()
        individual.features = self._create_features_part(4)
        return individual

But in population all individuals are objects of `my_custom_class` instead of `deap.creator.Individual`

What am I missing? Am I doing some stupid things here?

Greetings,
Filip

**Comment by fmder** [comment]
The problem with your code is that you never intanciate an individual in the create_individual. You receive the class not a new instance. Try the following

```python
def create_individual(self, icls):
        ind = icls()
        ind.parameters = self._create_parameters_part()
        ind.features = self._create_features_part()
        
        return ind
```

**Comment by palkafilip** [comment]
Wow, that was silly... Of course, it makes sense. Thank you for quick answer.
