### ISSUE TITLE
What determine the number of evaluations in one generation?

### ISSUE THREAD

**Issue by akselthele** [DEAP/deap#474]
In dynamic DE algorithm below ,What determine the number of evaluations in one generation?

gen	evals	error  	offline_error	avg     	max     
0  	60   	74.1562	108.358      	-137.757	-24.1562
1  	76   	74.1562	101.158      	-137.574	-24.1562
2  	170  	70.8881	85.2855      	-110.971	-20.8881
3  	272  	22.228 	69.1526      	-107.918	27.772  
4  	366  	20.2137	56.8148      	-89.2965	29.7863

**Comment by fmder** [comment]
The number of individuals modified by crossover and/or mutation.
