### ISSUE TITLE
When dealing with multi-objective, the result depends on the order of the objectives？

### ISSUE THREAD

**Issue by baozi-lala** [DEAP/deap#479]
When I use the code:
`creator.create("FitnessMulti", base.Fitness, weights=(-1.0, 1.0))`
I will get the result that minimizes the first objective：**(364.4, 2.26)**

but when I use the code below and exchange the order of two objectives :
`creator.create("FitnessMulti", base.Fitness, weights=(1.0, -1.0))`
I will get the result that maximize the first objective(The original second objective)：**(2.52, 403.5)**

**I compared the results with the results of running a single objective and found that it seems that only the first objective of each time has an impact on the result. Is this phenomenon normal?**

**Comment by fmder** [comment]
Yes, sorting is alphabetical (first objective first) when single objective functions. If you want to optimize multiple objectives you must use a multi objective selection (NSGA-II, NSGA-III, MO-CMAES).

This is the same as sorting sequences in Python

**Comment by baozi-lala** [comment]
I have used NSGA-II, but the result seems to try to optimize the first objective function, which is the same as the single objective optimization.

**Comment by fmder** [comment]
Our implementation of NSGA-II is correct. It consistently produces the same results as the original paper. Have you tried running your algorithm multiple time and comparing the averages?

**Comment by baozi-lala** [comment]
Yes, so in fact, the result of two objective functions is as same as the first one is not normal?  The program tries to satisfy multiple objectives at the same time instead of satisfying the first objective function. That means, my result is wrong because my code is wrong.

**Comment by fmder** [comment]
There shouldn't be any preference for objective order because sorting is made by pareto efficiency. Since genetic algorithm a inherently random, it is possible that between runs you get different results. At first sight, I seems to me that it is entirely possible that you just got unlucky with the reversed order experiment.

**Comment by baozi-lala** [comment]
Thank you for your patience, I will repeat the experiment again.
