### ISSUE TITLE
selectNSGA3 and selectNSGA3WithMemory return duplicates

### ISSUE THREAD

**Issue by markf94** [DEAP/deap#481]
### What I'm trying to do

I'm trying to solve a multi-objective optimization problem with NSGA-III. My cost function is expensive to evaluate and I want to maximize exploration of the search space. Thus, I want to ensure that there are no duplicates in my population. One way of doing that is to ensure that the `mutate` and `mate` functions return individuals that don't already exist in the population. That part is easy to do and totally fine. 

The next step is the selection that is performed through calling either the `selectNSGA3` or the `selectNSGA3WithMemory` function. On top of that, to ensure that there are no duplicates in the population from which we want to select I use `unique_individuals = list(set(pop + offspring))` (see code example below) before calling the `select` method.

### The issue

The issue is that the following lines of code;

```
# eliminate any duplicates
unique_individuals = list(set(pop + offspring))

# Use NSGA-III to select the next generation population from parents and offspring
pop = toolbox.select(unique_individuals, POP_SIZE)
```

result in a `pop`ulation with duplicate individuals even though the input space contained no duplicates.

### Code to reproduce the issue

Note, that this is some pretty stupid dummy code but it reproduces the problem.

```
import random

from deap import algorithms, base, creator, tools

POP_SIZE = 100

# Create some reference point
ref_points = tools.uniform_reference_points(1, 3)


class String:
    """
    Our custom type for the optimization. We optimize the list of letters in
    this example.
    """

    def __init__(self, letters):
        self.letters = letters

    def __repr__(self):
        return "".join(self.letters)


# Create classes
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", String, fitness=creator.FitnessMin)


def evaluate(individual):
    """
    Dummy evaluation function that counts the number of a's.
    """
    return (individual.letters.count("a"),)


def mutate(individual):
    """
    Dummy mutation function.
    """
    LETTERS = "abcdefghij"
    spot = random.choice(range(len(individual.letters)))
    individual.letters[spot] = random.choice(LETTERS)
    return (individual,)


def crossover(individual1, individual2):
    """
    Dummy crossover function.
    """

    half_way = len(individual1.letters) // 2
    individual1.letters = individual1.letters[:half_way] + individual2.letters[half_way:]
    individual2.letters = individual2.letters[:half_way] + individual1.letters[half_way:]
    return individual1, individual2


toolbox = base.Toolbox()
toolbox.register("individual", lambda: creator.Individual(list("bbbbbbbbbbbbbbb")))
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

toolbox.register("evaluate", evaluate)
toolbox.register("mate", crossover)
toolbox.register("mutate", mutate)
toolbox.register("select", tools.selNSGA3, ref_points=ref_points)


def main(seed=None):

    random.seed(0)

    pop = toolbox.population(n=POP_SIZE)

    # Evaluate the individuals with an invalid fitness
    invalid_ind = [ind for ind in pop if not ind.fitness.valid]
    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
    for ind, fit in zip(invalid_ind, fitnesses):
        ind.fitness.values = fit

    # Begin the generational process
    for gen in range(1, 100):
        offspring = algorithms.varAnd(pop, toolbox, 0.5, 0.5)

        # Evaluate the individuals with an invalid fitness
        invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
        fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
        for ind, fit in zip(invalid_ind, fitnesses):
            ind.fitness.values = fit

        # eliminate any duplicates
        unique_individuals = list(set(pop + offspring))

        # Use NSGA-III to select the next generation population from parents and offspring
        pop = toolbox.select(unique_individuals, POP_SIZE)

        # HERE'S THE ISSUE!
        if len(set(pop)) != POP_SIZE:
            print(f"Number of unique individuals to select from: {len(unique_individuals)}")
            print(f"Number of selected individuals: {len(pop)}")
            print(f"Number of unique selected individuals: {len(set(pop))}")
            raise ValueError

    return pop


if __name__ == "__main__":
    pop, stats = main()
```

### How to fix it

It's a simple one line change in the [`niching`](https://github.com/DEAP/deap/blob/05518db9d9cfe040cbd8e912ef7a1b3d6e53699b/deap/tools/emo.py#L624) function in `tools/emo.py` which I'm happy to implement after getting some feedback on this issue.

More concretely, on [line 627](https://github.com/DEAP/deap/blob/05518db9d9cfe040cbd8e912ef7a1b3d6e53699b/deap/tools/emo.py#L627) changing `while len(selected) < k:` to `while len(set(selected)) < k:` would fix the problem.

**Comment by fmder** [comment]
The behaviour comes from [line 643](https://github.com/DEAP/deap/blob/05518db9d9cfe040cbd8e912ef7a1b3d6e53699b/deap/tools/emo.py#L643). You are right that it may return twice the same individual, but the implementation is as described in algorithm 4 of the original paper _Deb, K., & Jain, H. (2013). An evolutionary many-objective optimization algorithm using reference-point-based nondominated sorting approach, part I: solving problems with box constraints. IEEE transactions on evolutionary computation, 18(4), 577-601._

The behaviour could be changed by using this line instead
```python
niche_individuals = numpy.flatnonzero(numpy.logical_and(niches == niche, available))
```

Thanks for pointing this out, I'll check what happens if I change it.

**Comment by markf94** [comment]
@fmder - I'm curious why you think this shouldn't make it into `master`. I'm happy to open an MR if you want...

**Comment by fmder** [comment]
I merged it into master didn't I? I did not released a new version though.

**Comment by markf94** [comment]
ooh sorry - I misread the status update and thought you just closed the issue. Thanks a lot for the fast feedback loop!
