### ISSUE TITLE
Is there any way to change the encoding mode 

### ISSUE THREAD

**Issue by TerenceLiu98** [DEAP/deap#484]
Usually, we use binary encoding in Genetic algorithm, but some how, we need to change into other encoding mode, is they any way we could achieve the changes inside the deap package? 

Looking forward to your reply!

**Comment by fmder** [comment]
I'm not sure understand your question. You want to do some part of the work in binary and some other in floating point?

**Comment by TerenceLiu98** [comment]
Yes, and we have solved the problem. Thanks a lot
