### ISSUE TITLE
DEAP Multiprocessing speed

### ISSUE THREAD

**Issue by SumuShan27** [DEAP/deap#485]
I am using the below sample code for OneMax problem (maximizing the number of ones of a bitstring) using DEAP package and multiprocessing.

I am unable to speed up the process using multiprocessing. I want to use this for a more complex problem before finding out what is the issue here.

Thank you.

import array
import multiprocessing
from multiprocessing import Pool
import random
import time
import numpy as np

from deap import algorithms
from deap import base
from deap import creator
from deap import tools

creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", array.array, typecode='b', fitness=creator.FitnessMax)

toolbox = base.Toolbox()

toolbox.register("attr_bool", random.randint, 0, 1)
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_bool, 10000)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

#OneMax problem is a simple problem consisting in maximizing the number of ones of a bitstring.
def evalOneMax(individual):
    return sum(individual),

toolbox.register("evaluate", evalOneMax)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)

if __name__ == "__main__":
#    Multiprocessing code  
    t1 = time.time()
    CPU_count = multiprocessing.cpu_count()-1   
    p = Pool(CPU_count)
    toolbox.register("map", p.map)
    

    pop = toolbox.population(n=1000)
    hof = tools.HallOfFame(1)

    algorithms.eaSimple(pop, toolbox, cxpb=0.5, mutpb=0.2, ngen=50, halloffame=hof)
    
    p.close()
    p.join()
    t2 = time.time()
    print("Multiprocessing with",CPU_count,"core(s) took",round((t2-t1),2),"s")

**Comment by fmder** [comment]
Your evaluation function is still too quick, on my laptop sum(range(10000)) takes 250us. That's way longer than the overhead of multiprocessing.

**Comment by SumuShan27** [comment]
Thank you for you reply, appreciate it.

I agree to what you are saying, but my point is - even for a more complex problems, this doesn't speed up.

We are overwriting the multiprocessing.Pool.map attribute with toolbox.map by the below lines,
**pool = multiprocessing.Pool()
toolbox.register("map", pool.map)**

But dont we have add another line to replace the function we would like to distribute? Like below,
**toolbox.map(evalOneMax, toolbox.individual())**

similar to how we multprocess normal functions like,
**pool.map(function, array of candidates)**
