### ISSUE TITLE
Error in multiprocessing example code

### ISSUE THREAD

**Issue by SumuShan27** [DEAP/deap#486]
I am referring to the OneMax using multiprocessing code provided as an example,
examples/ga/onemax_mp.py

I have replaced the simple onemax with slightly complex evolution function. Its not showing any speed improvement at all.

Do we need to do anything extra here? Really appreciate it.

**Comment by fmder** [comment]
I tested with the onemax_mp example with the following evaluation function

```python
def evalOneMax(individual):
    time.sleep(0.05)
    return sum(individual),
```

For 5 generations, it took 65.5 seconds without registering pool.map and 16.0 seconds with a pool of 4 workers on my laptop (core i5 dual core). Multiprocessing works out of the box.
