### ISSUE TITLE
Tiny bug in checkpoint example: open(checkpoint, "r") --> open(checkpoint, "rb")

### ISSUE THREAD

**Issue by TobiasGlaubach** [DEAP/deap#489]
Hi, 
Thanks for all the amazing work, there is a tiny bug in the checkpoint example, which made the example fail (at least on my machine). Bug:

```python
        with open(checkpoint, "r") as cp_file:
            cp = pickle.load(cp_file)
```

should be:

```python
        with open(checkpoint, "rb") as cp_file:
            cp = pickle.load(cp_file)
```

since python otherwise assumes some kind of chararray data.

Thanks for the amazing library and all the good work!

**Comment by TobiasGlaubach** [comment]
Link to example webpage:
https://deap.readthedocs.io/en/master/tutorials/advanced/checkpoint.html

**Comment by fmder** [comment]
Yeah, the tutorial has been written a long time ago when Python3 was not even out. We are in the process of re-writting the whole thing in Python3. I guess this will be part of it. Thanks.
