### ISSUE TITLE
'Individual' object has no attribute 'fitness'

### ISSUE THREAD

**Issue by jshobhit** [DEAP/deap#492]
Hey there, I'm trying to implement a custom DEAP script but my eaSimple algorithm fails after the first generation after an offspring has been generated. 

I've added a print statement to make sure that the offspring individuals are all of deap.creator.Individual type but the next line is where the error usually occurs. 

```
print(set([type(o) for o in offspring]))
invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
```

Here is the error output

> gen   nevals 
> 0       2     
>
> {<class 'deap.creator.Individual'>}
>
> Traceback (most recent call last):
>   File "evolve.py", line 188, in <module>
>     evolve(2, 2, 384, fitness.network_fitness, bounds)
>   File "evolve.py", line 168, in evolve
>     r = algorithms.eaSimple(population, toolbox, cxpb = 0, mutpb = 0.0, ngen = num_generations, verbose = True)
>   File "/home/shobhit/anaconda3/envs/tflow/lib/python3.6/site-packages/deap/algorithms.py", line 174, in eaSimple
>     invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
>   File "/home/shobhit/anaconda3/envs/tflow/lib/python3.6/site-packages/deap/algorithms.py", line 174, in <listcomp>
>     invalid_ind = [ind for ind in offspring if not ind.fitness.valid]
> AttributeError: 'Individual' object has no attribute 'fitness'`

How can it be possible that the Individual object has no attribute for fitness? This is how I have defined my Individual and how I'm generating the population.
```
creator.create('FitnessMax', base.Fitness, weights = (-1.0,))
creator.create('Individual', bitarray.bitarray , fitness = creator.FitnessMax)

toolbox.register('binary', gene.generate) 
toolbox.register('individual', tools.initIterate, creator.Individual, toolbox.binary)
toolbox.register('population', tools.initRepeat, list , toolbox.individual)
```

I'd love to know what I'm missing here coz I am lost right now. Thanks!

**Comment by jshobhit** [comment]
Just changed the creator Individual container type to list from bitarray.bitarray and it works fine.

**Comment by fmder** [comment]
Probably something with the new operator of that class that does not preserve subtype. We has similar issue with numpy and created a fix in the creator. You can have a look if you want https://github.com/DEAP/deap/blob/master/deap/creator.py#L51.
