### ISSUE TITLE
versioning scheme according to semver.org?

### ISSUE THREAD

**Issue by joernhees** [DEAP/deap#51]
this is more a suggestion than a bug-report.

A lot of projects use [Semantic Versioning](http://semver.org) as versioning scheme. Following it has some immediate benefits for people using a lot of frameworks/libraries (e.g., not having to learn a special meaning for the version of each of those libs).

I just thought i'd bring this up as the [porting guide](http://deap.readthedocs.org/en/latest/porting.html) seems to imply you're using some other versioning scheme.

**Comment by fmder** [comment]
The porting guide was made to port 0.9 to 1.0. Our versioning system is quite similar to the one pointed.

patch: bug fix
minor: new features
major: API break

Thanks for pointing this out.
