### ISSUE TITLE
How can I define my fitness functions. 

### ISSUE THREAD

**Issue by langongjin** [DEAP/deap#512]
Hi, 
I am running PSO and EDA for my fitness functions. So far, the default code is working on my computer. But, I cannot find where I can define my own fitness functions. How the default code creates the objective functions? Furthermore, I need to control the range of variables. Then, I can run it quickly for my situation.
Thanks!

**Comment by fmder** [comment]
What have you tried?

**Comment by langongjin** [comment]
sorry for the confusion. I am running PSO (basic.py) and EDA (emna.py, I hope this is the right code to run for EDA). But I do not know how to define my own fitness functions with the expected range of variables.

**Comment by fmder** [comment]
Here is the part of the tutorial talking about it. 

https://deap.readthedocs.io/en/master/overview.html#operators

**Comment by langongjin** [comment]
Thanks for the answer. It is clear that 'create' makes objective functions. But where is the function body? I checked creator.py, but I did not function where I can write my objective functions. I am not familiar with Python, I am a C++ guy. In C++, we have specific objective functions that we can call it or create a new function in the same class where the existing functions are.

**Comment by fmder** [comment]
The function body is in the evaluate function.

```
def evaluate(individual):
    return sum(individual),
```

**Comment by langongjin** [comment]
Thanks! 
Thus, the sum function is the objective function If I run basic.py of PSO, am I right?
But I found the following code in basic.py of PSO.
```
    for g in range(GEN):
        for part in pop:
            part.fitness.values = toolbox.evaluate(part)
```
where `toolbox.evaluate(part)` links to the following function in `test_benckmarks.py`
```
def evaluate(individual):
            """Simplest evaluation function."""
            return individual
```
where is not a sum function and nothing inside of this function. Therefore, I am confused now.

**Comment by fmder** [comment]
I’m not sure you read the section I sent earlier.

**Comment by langongjin** [comment]
Hi, Yes, I did and I read it again just now. I think now I understand more, but I do still not know where I can change the code for my objective functions on my local code that I downloaded from DEAP. I know somewhere I can define my objective functions like below.
```
def evaluate(individual):
    # Do some hard computing on the individual
    a = sum(individual)
    b = len(individual)
    return a, 1. / b
```
But I do not know where it should be. Could you point it out for me in detail? Thanks!

**Comment by fmder** [comment]
It is the line

`toolbox.register("evaluate", evaluateInd)`

**Comment by langongjin** [comment]
Thanks. I got it. The answer I needed is the functions in deap/doc/code/benchmarks. all functions are defined there. I can create a new function there and register it in the main function.

**Comment by fmder** [comment]
No you can define the function anywhere in your code then register it in the toolbox.
