### ISSUE TITLE
how to generate all the expressions on a given primitive set?

### ISSUE THREAD

**Issue by nickhuangxinyu** [DEAP/deap#520]
I think when i confirmed the primitive set. the expression tree space is confirmed( the number of expression trees for a fixed depth).

How can i generate them all?

I think genFull or genHalf is randomly generator, how can i generate all without missing?

Thanks

**Comment by nbro** [comment]
@nickhuangxinyu What do you mean? Do you mean how you can generate all possible trees?

**Comment by nickhuangxinyu** [comment]
@nbro yes

**Comment by fmder** [comment]
You'd need a good combinatorial logic for every node.
