### ISSUE TITLE
History does not store fitness values

### ISSUE THREAD

**Issue by alxhoff** [DEAP/deap#531]
I am not sure if this is by design but I am struggling to find a way to have the fitness values of all individuals in my `genealogy_history` stored from when they were evaluated during the programs execution. 

Does one have to do this manually? Doing something similar to the following maybe?

```
def evaluate_individual(individual):
    ret = individual.evaluate(
        ...
    )
    individual.fitness.values = ret
    return ret
```

I have been looking around and have been unable to find a way for storing the finesses of all individuals (ideally within the individuals) that were created during execution. I am wanting to plot the finesses of all the created individuals and evaluating each one would be take a long time and is not feasible. 

I am doing the following for storing my history

```
history = tools.History()
toolbox.decorate("mate", history.decorator)
toolbox.decorate("mutate", history.decorator)

pop = toolbox.population(n=pop_size)
history.update(pop)

pop, logbook = algorithms.eaSimple(
        pop,
        toolbox,
        cxpb=0.5,
        mutpb=0.2,
        ngen=gen_count,
        stats=stats,
        halloffame=hof,
        verbose=True,
    )
```

Cheers

**Comment by DMTSource** [comment]
Inside the evo algorithm(copy and paste it to your script to modify) you can form list, dict, or dataframe to track fitness per gen. Or, when fitness it applied to the individuals, you could try adding the information you need to each individual as it is an object.

https://github.com/DEAP/deap/blob/master/deap/algorithms.py#L152
https://github.com/DEAP/deap/blob/master/deap/algorithms.py#L174

After each of these lines in the loop, you could form a list or dict or dataframe and store it inside each individual to maintain info about its personal updates.

```
# dict example, but may not yield what you want as individuals live and die sporadically
if hasattr(ind, 'updates'):
    ind.updates[gen] = fit
else:
    ind.updates= {}
    ind.updates[gen] = fit
```
Also some discussion here on the same topic with possibly more info:
https://groups.google.com/g/deap-users/c/DGMFrxPBvLg/m/2LAlZGGMAwAJ

**Comment by alxhoff** [comment]
Thanks for the reply. That was going to be my next approach. Sorry for my slow reply over the holidays!

Cheers
