### ISSUE TITLE
TypeError: Both weights and assigned values must be a sequence of numbers when assigning to values of <class 'deap.creator.FitnessMin'>. Currently assigning value(s) <map object at 0x0000015D88A3C0A0> of <class 'map'> to a fitness with weights (-1.0,).

### ISSUE THREAD

**Issue by Ascendina** [DEAP/deap#535]
The error is this:

TypeError: Both weights and assigned values must be a sequence of numbers when assigning to values of <class 'deap.creator.FitnessMin'>. Currently assigning value(s) <map object at 0x0000015D88A3C0A0> of <class 'map'> to a fitness with weights (-1.0,).

And it occurs, when I'm trying to calculate the validation value to the best individuo of the iteration:
        
        best_ind = best_pop(population)
        best_val_ind = best_pop(population)
        if config["validation_flag"]:
            fitnessv_best = toolbox.map(toolbox.evaluate_val, [best_ind])
            best_val_ind.fitness.values = fitnessv_best

I'm really having trouble with types with some changes in the easimple to have one validating stage.

Could anyone help me?

**Comment by Ascendina** [comment]
Hi guys,

I solve my problem, but I didn't understand why.
I change the acess to the fitness to a for and work.

#calculating the validation value - best ind
        best_ind = best_pop(population)
        if config["validation_flag"]:
            fitnessv_best = toolbox.map(toolbox.evaluate_val, [best_ind])
            for i, fit in enumerate(fitnessv_best):
                print(fit)
                mseValidation = fit

But I didn't understand why.
Could anyone help me with this question?!

**Comment by DMTSource** [comment]
You have:
`fitnessv_best = toolbox.map(toolbox.evaluate_val, [best_ind])`

You are evaluating a single individual, but in a list to form the batch for map, so you get a list of fitness back: 
`fitnessv_best = [(fitness_1,),] #prob something like this`

In this case just 1 tuple of fitness is in the list and you want that to go into _best_val_ind.fitness.values_. This is why your for loop happened to work as a fix; it iterated over the list and took the single tuple out for you.

So you probably need the first item in the list fitnessv_best, or:
`best_val_ind.fitness.values = fitnessv_best[0]`
