### ISSUE TITLE
Competitive Coevolution Example

### ISSUE THREAD

**Issue by seanng-1** [DEAP/deap#544]
Hi,

I was searching through the docs and saw that there was an example for cooperative coevolution but there was no example for the competitive version. I was scrolling through the old releases and found this http://deap.gel.ulaval.ca/doc/0.8/examples/coev_comp.html but unfortunately that was also blank. 

I was wondering if I could receive any guidance on how to get started with such an algorithm in DEAP. I am looking to use two populations, with the first evolving some trajectories for a robotic arm whilst the second population will be used to tune physics parameters within another simulation. I currently have the first population working in isolation  as a genetic algorithm (using my own function not DEAP) but would find it very helpful if someone could point me in the right direction with the competitive approach.

**Comment by fmder** [comment]
You could look at the hillis example, is shows host parasite paradigm
