### ISSUE TITLE
example for plotting data with matplot

### ISSUE THREAD

**Issue by liyigerry** [DEAP/deap#55]
I notice the beautiful video of the algorithm in action, plotted with matplotlib. I can not find this code. Anybody have shared this?
https://www.youtube.com/v/f3MW2krobpo?version=3&feature=player_detailpage

**Comment by fmder** [comment]
Actually, we did the video by saving one figure for every generation and videoify it with ffmpeg. It was done with DEAP pre-0.5 and I think the code is lost somewhere in the void of development, I should be hard to reimplement.

We woul'd be glad to add it if you make a pull request.

**Comment by liyigerry** [comment]
@fmder Thanks your reply. I pulled it.
