### ISSUE TITLE
how can I create an individual an add in the population?

### ISSUE THREAD

**Issue by Ascendina** [DEAP/deap#563]
I want to create only one individual in the population. 

I saw the link:
https://deap.readthedocs.io/en/master/tutorials/basic/part1.html?highlight=seeding#seeding-a-population

But it shows how to create all the individuals in the population. I just want to seed one individual.

Could someone help me with this issue?!

Thank you for the attention

**Comment by fmder** [comment]
It depends on how you are using DEAP. Do you mean that you want to create a random population and add some individuals in it? Population are lists, you can directly append to them.

**Comment by Ascendina** [comment]
Thank you for your answer!

I want to create a random population and add one individual that isn't random.

I want to use a gp.primitive tree. Trying yesterday to do this, I came to this code:

def initIndividual(icls, content):
    return icls(content)

def initSeed(ind_init, tree):
    return ind_init(tree)


#main code
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("FitnessTest", base.Fitness, weights=(-1.0,))
creator.create("Individual", gp.PrimitiveTree, fitness=creator.FitnessMin)

toolbox = base.Toolbox()
#for seeding
toolbox.register("individual_seed", initIndividual, creator.Individual)
toolbox.register("guess_seed", initSeed, toolbox.individual_seed)

#Call the function in code
seed = toolbox.guess_seed(newSeed)

Thank you for all the help!
