### ISSUE TITLE
Examples wont work

### ISSUE THREAD

**Issue by Erlix322** [DEAP/deap#570]
unfortunately none of the examples work and they are pretty outdated

Toolbox seems to have changed as it constantly produces errors (see below)

`Instance` of 'Toolbox' has no 'population' `memberpylint(no-member)`

At first glance it looks really promising but the lack of documentation does not want me to look further.

**Comment by fmder** [comment]
Linters are unable to detect add functions in the toolbox as they are added on the fly.
