### ISSUE TITLE
Cigar's function seems incorrect

### ISSUE THREAD

**Issue by Dntfreitas** [DEAP/deap#572]
It seems that Cigar's function is incorrect.

According to [your docs](https://deap.readthedocs.io/en/master/api/benchmarks.html#deap.benchmarks.cigar), the sum starts at *i=1*, which is the second element of the *individual* array. This is correct.

However, in the code, the function is computed as: `individual[0]**2 + 1e6 * sum(gene * gene for gene in individual)`; that is, is using all the elements of the array for the sum.

**Comment by fmder** [comment]
I think the usual sums in math notation use 1 as first elements. I don't remember seeing 0 very often.

**Comment by Dntfreitas** [comment]
This is the original Cigar's function:
![imagem](https://user-images.githubusercontent.com/8163918/118542645-31bf8f80-b74b-11eb-85fd-513423655b1a.png)

In [your docs](https://deap.readthedocs.io/en/master/api/benchmarks.html#deap.benchmarks.cigar):
![imagem](https://user-images.githubusercontent.com/8163918/118542833-70554a00-b74b-11eb-838a-d5b52916cb1e.png)

**Both formulations are correct.** 

The problem is in the code. The function is computed as: `individual[0]**2 + 1e6 * sum(gene * gene for gene in individual)`; that is, is using all the elements of the array in the summation, when it should start from the second element.

**Comment by fmder** [comment]
You are right! Fixed in 3cb010b
