### ISSUE TITLE
Link of DEAP uses in README

### ISSUE THREAD

**Issue by rodrigo-arenas** [DEAP/deap#576]
Hi, I'd like to add this information to the section "Projects using DEAP" in the README file, I'm not sure if I could open a pull request including it or if send it over here the description is ok. 
Thanks in advance!
The description is as follows:

DEAP is used in [Sklearn-genetic-opt](https://github.com/rodrigo-arenas/Sklearn-genetic-opt), an open source tool that uses evolutionary programming to fine tune machine learning hyperparameters.

**Comment by fmder** [comment]
Done! Thanks and sorry for the delay :)
