### ISSUE TITLE
the problem of generating expression of Strongly Typed GP

### ISSUE THREAD

**Issue by liningbo** [DEAP/deap#579]
version : 1.2
problem:  deap can not add terminal when  primitive set has not suitable type but terminal set has.

example:
pset = gp.PrimitiveSetTyped('main', [], pd.DataFrame)

pset.addPrimitive(func1, [pd.DataFrame, pd.DataFrame], pd.DataFrame)
pset.addPrimitive(func2, [pd.DataFrame,int], pd.DataFrame)

pset.addTerminal(terminal=pd.DataFrame(), ret_type=pd.DataFrame,name='t1')
pset.addTerminal(1, int, name=str(1))

expr = gp.genFull(pset, min_=1, max_=10)
tree = gp.PrimitiveTree(expr)
print(str(tree))

the code will the error:
IndexError: The gp.generate function tried to add a primitive of type '<class 'int'>', but there is none available.

I think though primitive set has not the function which will return int, but the terminal set has the constant of type int. so deap should add terminal of type int into the expression but not raise error.

**Comment by jasonzutty** [comment]
I believe this issue comes from predetermined tree depth that is trying to be filled out. A workaround in the mean time is to add a pass through primitive:

```
def pass_through(x):
    return x

pset.addPrimitive(pass_through, [int], int)
```

**Comment by liningbo** [comment]
> I believe this issue comes from predetermined tree depth that is trying to be filled out. A workaround in the mean time is to add a pass through primitive:
> 
> ```
> def pass_through(x):
>     return x
> 
> pset.addPrimitive(pass_through, [int], int, name='pass_int')
> ```

I used the method to avoid the problem, but this led the expressions to be redundant, and not graceful.

**Comment by fmder** [comment]
Yes but logically it does not make sense to ask the program to build full trees if for some non-leave it is impossible to find an other non-leave if the required type. I guess there could be a tree generation utility that allows for it ...

**Comment by BrandonDotLin** [comment]
> > I believe this issue comes from predetermined tree depth that is trying to be filled out. A workaround in the mean time is to add a pass through primitive:
> > ```
> > def pass_through(x):
> >     return x
> > 
> > pset.addPrimitive(pass_through, [int], int, name='pass_int')
> > ```
> 
> Thank you for reply, I used the method to avoid the problem, but this led the expressions to be redundant, and not graceful.

Hi @liningbo, have you figured out how to avoid this problem?

**Comment by liningbo** [comment]
> > > I believe this issue comes from predetermined tree depth that is trying to be filled out. A workaround in the mean time is to add a pass through primitive:
> > > ```
> > > def pass_through(x):
> > >     return x
> > > 
> > > pset.addPrimitive(pass_through, [int], int, name='pass_int')
> > > ```
> > 
> > 
> > Thank you for reply, I used the method to avoid the problem, but this led the expressions to be redundant, and not graceful.
> 
> Hi @liningbo, have you figured out how to avoid this problem?

@BrandonDotLin  I just do  as jasonzutty siad, make a function to return a int value equal to the input of the function.

**Comment by wukan1986** [comment]
```python
        else:
            try:
                prim = random.choice(pset.primitives[type_])
            except IndexError:
                # ===========================
                term = random.choice(pset.terminals[type_])
                if isclass(term):
                    term = term()
                expr.append(term)
                continue
                # ===========================
                _, _, traceback = sys.exc_info()
                raise IndexError("The gp.generate function tried to add "
                                 "a primitive of type '%s', but there is "
                                 "none available." % (type_,)).with_traceback(traceback)
            expr.append(prim)
            for arg in reversed(prim.args):
                stack.append((depth + 1, arg))
```

you can add some code to `generate` in `gp.py`

**Comment by Happylinzy** [comment]
Hope this pull request can be merged ASAP.

**Comment by fmder** [comment]
This cannot be merged as it breaks the logic of a full tree.
