### ISSUE TITLE
Convergence on local optima in PSO

### ISSUE THREAD

**Issue by Nistha-gif** [DEAP/deap#589]
Dear sir/mam,
             I am using DEAP for my research problem on a variant of the Vehicle Routing Problem. I have observed that the program pre-maturely converges on local optima. Can you please suggest, how to avoid this using an example or a function?

**Comment by jameshughes89** [comment]
I am unclear if this is describing an issue with DEAP, or if this is an issue you are having with tuning your PSO. 

Please elaborate on the details of your issue so individuals may look into this.

**Comment by fmder** [comment]
Premature convergence is generally fought with higher mutation rate. In the PSO algorithm this would translate to a higher speed or momentum if I remember correctly.
