### ISSUE TITLE
Unresolved Attribute Reference Flag in PyCharm Issue/Question

### ISSUE THREAD

**Issue by matt-c-dev** [DEAP/deap#599]
Hi all,

I have been using DEAP for some school stuff and I have noticed that when referencing operators registered to the toolbox, my IDE will flag the method as an Unresolved attribute, however it runs just fine when the code is run.

Perhaps the documentation could be updated to account for this warning.

**Comment by fmder** [comment]
Unfortunately, functions are created on the fly and it is understandable that IDE can't catch them. It'd need to run the full code.
