### ISSUE TITLE
Can't get attribute rand101 on module deap.gp

### ISSUE THREAD

**Issue by BrandonDotLin** [DEAP/deap#628]
when i tried to run symbreg_ray.py from https://github.com/DMTSource/deap_ray/blob/master/symbreg_numpy_ray.py in my ray cluster, below errors occures:
AttributeError: Can't get attribute 'rand101' on <module 'deap.gp' from '/home/ray/anaconda3/lib/python3.8/site-packages/deap/gp.py'>

any suggestions?

**Comment by fmder** [comment]
Not sure, but in multiprocessing setups like that, often the creator is not initialized on remote processes.

**Comment by fmder** [comment]
More detailed error trace might help too.

**Comment by cactusWhiskey** [comment]
I don't think gp.py has anything named rand101 in it

**Comment by fmder** [comment]
@cactusWhiskey It should have been added with the call ``pset.register(...)``

**Comment by cactusWhiskey** [comment]
Oh I see. Yeah then as you mentioned it's almost certainly the issue with the creator not getting initialized on the remote workers. I've run into that issue a bit before. You could try just copying the creator code into the remote worker somewhere.
