### ISSUE TITLE
Tournament selection in NSGAII fails with k smaller individuals size

### ISSUE THREAD

**Issue by Leviathan321** [DEAP/deap#631]
I was applying the nsgaII Algorithm in DEAP (link below) and encountered a problem with my population size when using the implemented Tournament-Selection algorithm. I encountered that if *k* < |*individuals*|  the algorithm generates a set with size not k. If passing *k* == |*individuals*|  and  |*individuals*|  % 4 != 0, some exception is raised. This case is consider correct in the implementation (https://github.com/DEAP/deap/blob/master/deap/tools/emo.py#L189-L193).

Why does the selection algorithm stick to this restricted approach processing groups of 4 elements making this approach so specific?

https://github.com/DEAP/deap/blob/master/deap/tools/emo.py#L145-L195

**Comment by Leviathan321** [comment]
I closed this without purpose. Can someone confirm this, and reopen the issue? Thanks

**Comment by fmder** [comment]
What fails? What is the error message?

Regarding your second question, this is because the original paper implements it this way. I often used NSGA-II as the single selection operator without any problem.

**Comment by Leviathan321** [comment]
I have changed the original NSGAII algorithm so that I am passing a number smaller than the actual population size for k (e.g. 9, when Population Size is 10):


```python
...
 #Begin the generational process
    for gen in range(1, NGEN):
        # Vary the population
        offspring = tools.selTournamentDCD(pop, len(pop)-1)
        offspring = [toolbox.clone(ind) for ind in offspring]

        for ind1, ind2 in zip(offspring[::2], offspring[1::2]):
            if random.random() <= CXPB:
                toolbox.mate(ind1, ind2)

            toolbox.mutate(ind1)
            toolbox.mutate(ind2)
            del ind1.fitness.values, ind2.fitness.values
...
```

I get the following exception:


```
Traceback (most recent call last):
  File "C:\Users\XXX\Documents\Projects\FOCETA\python_algorithm\nsgaII_dt.py", line 297, in <module>
    pop_run_bi, stats2 = nsgaII_testcase(initial_pop=pop_regions[i], var_min=bound[0], var_max=bound[1])
  File "C:\Users\XXX\Documents\Projects\FOCETA\python_algorithm\nsgaII_dt.py", line 174, in nsgaII_testcase
    offspring = tools.selTournamentDCD(pop, len(pop)-1)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\deap\tools\emo.py", line 191, in selTournamentDCD
    chosen.append(tourn(individuals_1[i+2], individuals_1[i+3]))
IndexError: list index out of range
```
