### ISSUE TITLE
Pass an argument to DeltaPenality function

### ISSUE THREAD

**Issue by FedericoMz** [DEAP/deap#632]
How can I pass an argument to my DeltaPenality function?

Starting from [the example in the documentation](https://deap.readthedocs.io/en/master/tutorials/advanced/constraints.html), let's say my individual can only assume values between _a_ and _b_, and I need to pass those values as arguments.

```
def feasible(individual, a, b):
    if a < individual[0] < b:
        return True
    return False
```

I tried
`toolbox.decorate("evaluate", tools.DeltaPenality(feasible, 7.0), a=a, b=b)`

But I got
`TypeError: feasible() got an unexpected keyword argument 'a'`

**Comment by amarinov96** [comment]
Wrap it with a partial function, you can't pass them directly to DeltaPenalty. 

```
from functools import partial

def feasible(individual, a, b):
    if a < individual[0] < b:
        return True
    return False

feasible_wrapped = partial(feasible, a=a, b=b)

toolbox.decorate("evaluate", tools.DeltaPenalty(feasible_wrapped, 7.0))

```

**Comment by FedericoMz** [comment]
> Wrap it with a partial function, you can't pass them directly to DeltaPenalty.
> 
> ```
> from functools import partial
> 
> def feasible(individual, a, b):
>     if a < individual[0] < b:
>         return True
>     return False
> 
> feasible_wrapped = partial(feasible, a=a, b=b)
> 
> toolbox.decorate("evaluate", tools.DeltaPenalty(feasible_wrapped, 7.0))
> ```

This worked really well! Thank you, @amarinov96
