### ISSUE TITLE
NaN when perform crossover operations with cxSimulatedBinaryBounded

### ISSUE THREAD

**Issue by Leviathan321** [DEAP/deap#653]
I get the following error when I perform search including the crossover function cxSimulatedBinaryBounded:

```
C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\deap\tools\crossover.py:340: RuntimeWarning: invalid value encountered in double_scalars
  beta_q = (1.0 / (2.0 - rand * alpha)) ** (1.0 / (eta + 1))
```

This results in a NaN fitness values. I suppose this has to do with division by zero? Is there a way to avoid this?

**Comment by aabmets** [comment]
@Leviathan321 
Please share your code what caused this error. 
It is essential to know the datatypes and the values of the parameters 
which were fed into the function to diagnose this issue correctly.

**Comment by Leviathan321** [comment]
Thanks, I debugged this further and opened a more concrete issue https://github.com/DEAP/deap/issues/655.
