### ISSUE TITLE
selTournament always does max(...) regardless of maximization or minimization problem

### ISSUE THREAD

**Issue by davidmurray** [DEAP/deap#680]
Hello,

For a minimization problem, shouldn't the `selTrournament` function perform a `min(...)` rather than a `max(...)`? For minimization problems, a lower fitness level is better. Perhaps I am misunderstanding something...

https://github.com/DEAP/deap/blob/fa3abe189e71cb7afef71e0acaaf1a635f083281/deap/tools/selection.py#L63-L68

Thanks,
David

**Comment by fmder** [comment]
That is because fitness are multiplied by weights. So the optimization
always go the same side on weighted fitness.

Le mar. 20 déc. 2022, 14 h 15, David Murray ***@***.***> a
écrit :

**Comment by davidmurray** [comment]
Ah! Makes sense! Thanks :)
