### ISSUE TITLE
Is DEAP maintained?

### ISSUE THREAD

**Issue by bje-** [DEAP/deap#693]
Issues and PRs seem to be dealt with very slowly. Are more maintainers welcome to keep DEAP maintained? A lot of us depend on it.

**Comment by fmder** [comment]
I welcome new developers :)!

Le mar. 28 mars 2023, 18 h 05, Ben Elliston ***@***.***> a
écrit :

**Comment by bje-** [comment]
If you can add me as a member, I'll start working on clearing the issue backlog.
