### ISSUE TITLE
Support for Linux ARM aarch64 

### ISSUE THREAD

**Issue by LordFrankenstien** [DEAP/deap#721]
I work for an organization that is trying to move their server to ARM architecture to match the new Apple Silicon laptops.  Using the conda environment can't find a binary for deap.  I can build it locally, but that breaks down the automation around installing new conda environments.  I'd be willing to occasionally build and push the Linux ARM build if someone can point me to what is needed. I've found these instructions, but I'm not 100% sure this is the correct method to get something on conda-forge. https://packaging.python.org/en/latest/tutorials/packaging-projects/ 
I'd like to see the Linux ARM support here, at least I think that is what I need for conda to be able to install it. https://anaconda.org/conda-forge/deap

**Comment by fmder** [comment]
Maybe a good place to start would be the ARM section in the .azure-pipelines/cd.yaml. It should build the ARM wheel automatically. If it doesn't there is something wrong that I didn't detected. If you can run manually every step on your system and help debug it, that would be helpful. I don't have access to a ARM system.

**Comment by LordFrankenstien** [comment]
Thanks for the pointer there.  I have never used .azure-pipelines before so didn't even notice it or think to look there.  I'm not 100% sure what I am looking at, but the little bit I kinda understand makes me thing the automated process should be generating the arm binary (if it isn't failing) and pushing it to pypi.   I'm not sure why it isn't making it to conda/conda-forge. 
I'm also a little suprised it is not almost identical to the linux section about, except asking for ARM instances, which Azure has had or almost a year.   I'm not understanding why it is launching a docker container (I assume all these builds are probably already running in docker containers anyway), and running in a different way than the other pipelines.  Unless that is a cross-compiler docker container and this is a hold over from before there was Azure support for ARM. 
-- I will try to run the commands in an instance I have in AWS and see what happens.

**Comment by fmder** [comment]
I see, can you try to pip install it instead of conda?

I will definitely try the ARM instances on Azure. I didn't knew about it.

**Comment by LordFrankenstien** [comment]
I was able to get a pip install to work from within conda this morning.  I don't know if that is because you made changes or if it would have always worked that way.

**Comment by fmder** [comment]
Great to hear that, I was really afraid that I would have to debug something on that front 😂. I'll close the issue.
