### ISSUE TITLE
In the example bbob.py，how can I get the "fgeneric" and "bbobbenchmarks" module?

### ISSUE THREAD

**Issue by xuhao0521** [DEAP/deap#722]
https://github.com/DEAP/deap/blob/master/examples/bbob.py

how can I get the "fgeneric" and "bbobbenchmarks" module?

**Comment by fmder** [comment]
BBOB can be found [here](https://numbbo.github.io/workshops/)

fgeneric is also in the same package. Instructions can be found in the BBOB EEBSITE.
