### ISSUE TITLE
ImportError: No module named copyreg

### ISSUE THREAD

**Issue by ShuC-Pola** [DEAP/deap#747]
Hi! 
I'm using Python 2.7, and when I import creator from the deap package, I constantly encounter the error "No module named copyreg." I suspect that in Python 2.7, the module is named copy_reg instead of copyreg, but I'm not sure how to rename this file so that I can import it. 
Any help would be appreciated! Thanks in advance!

**Comment by fmder** [comment]
Unfortunately Python 2.7 has been out of support for many years now, so
there won't be any fix on the github repo. However, you could clone the
repository fix the file and install from source. From the root directory,
just type "pip install ."

Le jeu. 13 juin 2024, 14 h 38, ShuC-Pola ***@***.***> a
écrit :
