### ISSUE TITLE
Callback Function in Deap

### ISSUE THREAD

**Issue by PauloDoMonte** [DEAP/deap#748]
Does anyone know of a way to add a callback function within eaSimple.
This function would be used to check whether at one time the pop had a certain value and if so, it could terminate the program.
It would be another early_stop that is available in keras.

`def def_callback(pop):
     ...... #What my function does

resultado, log = algorithms.eaSimple(pop, toolbox, cxpb=cx_pb_, mutpb=mutpb_, halloffame=hof, stats=estatistica,
                                         ngen=1000, verbose=True, callback=def_callback)`

**Comment by fmder** [comment]
The recommended way would be to copy the whole eaSimple function in your
code and add the part you need. We intentionally avoided callbacks to
encourage users to understand entirely  the algorithms.

Le sam. 15 juin 2024, 11 h 55, Paulo Do Monte ***@***.***> a
écrit :

**Comment by Lucandia** [comment]
I understand the philosophy of avoiding callbacks, but in my case, I'd like to do a simple thing: at the end of each generation send the statistics to another function (to write the results on a Streamlit WebApp). In this case, it doesn't really have to do anything to do with understanding the algorithms, it's just to show the results in real-time. Copy/pasting the code is messy, especially if it is the exact same function as the eaSimple, but with a silly callback. I don't think there is a big problem with adding a simple callback option or that would be tricky to implement. I'd like it as a feature

**Comment by PauloDoMonte** [comment]
I wasn't familiar with the philosophy of avoiding callbacks, but I find it interesting. I wish there was a way to still use callbacks, especially for people in the physics field who may not be very familiar with programming. It would make the research process easier since they could spend more time being a physicist and thinking about an analytical or numerical solution, rather than figuring out a solution in terms of algorithms. But I understand your point. I'll look into this algorithm more and work on my own implementation.

**Comment by wangyexiang** [comment]
> I understand the philosophy of avoiding callbacks, but in my case, I'd like to do a simple thing: at the end of each generation send the statistics to another function (to write the results on a Streamlit WebApp). In this case, it doesn't really have to do anything to do with understanding the algorithms, it's just to show the results in real-time. Copy/pasting the code is messy, especially if it is the exact same function as the eaSimple, but with a silly callback. I don't think there is a big problem with adding a simple callback option or that would be tricky to implement. I'd like it as a feature

+1
