### ISSUE TITLE
AttributeError: 'PrimitiveSet' object has no attribute '__name__'.

### ISSUE THREAD

**Issue by artem-arefev32** [DEAP/deap#751]
Hi!
I'm using python 3.10 and following the DEAP github example for symbolic regression with ADFs. When I add an automatically defined function to my main primitive set, I encounter the error: 
"File ... adfset1.addPrimitive(adfset2, 2)
  File "/u/artema_guest/.local/lib/python3.10/site-packages/deap/gp.py", line 462, in addPrimitive
    PrimitiveSetTyped.addPrimitive(self, primitive, args, \__type\__, name)
  File "/u/artema_guest/.local/lib/python3.10/site-packages/deap/gp.py", line 357, in addPrimitive
    name = primitive.\__name\__
AttributeError: 'PrimitiveSet' object has no attribute '\__name\__'. Did you mean: '\__ne\__'?"

I suspect that the "PrimitiveSet" class used to instantiate ADF primitives does not have the "\__name\__" attribute, as the  "PrimitiveSet" class inherits from the "PrimitiveSetTyped" class which only has the "name" attribute and not "\__name\__".

I am able to go around this by explicitly specifying the name parameter upon instantiation of the primitive, but this is a clear issue. Or maybe I'm doing something wrong...

Any help would be appreciated. Thanks in advance.

**Comment by fmder** [comment]
It looks like your are adding a primitive set with add primitive and not a primitive?
