### ISSUE TITLE
pip install issue - README.md not found

### ISSUE THREAD

**Issue by phelantrinh** [DEAP/deap#79]
I am getting this issue when trying to install the package in VS2013 (PTVS). I am also getting this from the command line as well. I am using Python 3.4.

    Installing 'deap'
    Collecting deap
      Using cached deap-1.0.2.post1.tar.gz
        warning: pypandoc module not found, could not convert Markdown to RST
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\DOCUME~1\USER\LOCALS~1\Temp\pip-build-a1bo2jcu\deap\setup.py", line 22, in <module>
            long_description=read_md('README.md'),
          File "C:\DOCUME~1\USER\LOCALS~1\Temp\pip-build-a1bo2jcu\deap\setup.py", line 13, in <lambda>
            read_md = lambda f: open(f, 'r').read()
        FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
        Complete output from command python setup.py egg_info:
        warning: pypandoc module not found, could not convert Markdown to RST
        
        Traceback (most recent call last):
        
          File "<string>", line 20, in <module>
        
          File "C:\DOCUME~1\USER\LOCALS~1\Temp\pip-build-a1bo2jcu\deap\setup.py", line 22, in <module>
        
            long_description=read_md('README.md'),
        
          File "C:\DOCUME~1\USER\LOCALS~1\Temp\pip-build-a1bo2jcu\deap\setup.py", line 13, in <lambda>
        
            read_md = lambda f: open(f, 'r').read()
        
        FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
        
        ----------------------------------------
        Command "python setup.py egg_info" failed with error code 1 in C:\DOCUME~1\USER\LOCALS~1\Temp\pip-build-a1bo2jcu\deap
    'deap' failed to install. Exit code: 1

**Comment by phelantrinh** [comment]
This appears to be an issue with 1.0.2. I can install 1.0.1 fine.

**Comment by cmd-ntrf** [comment]
Thanks for the report. The file `MANIFEST.in` did not include markdown file (*.md) when bundling the source, therefore the `README.md` was not included and it spawned the error you mention.

I have modified the MANIFEST.in in both master and 1.0.x branch, and bundle a new release: `deap-1.0.2.post2.tar.gz`, which is now on pypi.

Let us know if you still have issues with this new release.

**Comment by elazar** [comment]
@cmd-ntrf I'm still having this issue with 1.0.2.post2.

```
# cat requirements.txt
-e git+https://github.com/jleclanche/fireplace.git#egg=fireplace
deap
# ~/venv/bin/pip install -r requirements.txt
Obtaining fireplace from git+https://github.com/jleclanche/fireplace.git#egg=fireplace (from -r requirements.txt (line 1))
  Updating /root/venv/src/fireplace clone
Collecting deap (from -r requirements.txt (line 2))
  Downloading deap-1.0.2.post2.tar.gz (852kB)
    100% |################################| 856kB 770kB/s
    Complete output from command python setup.py egg_info:
    warning: pypandoc module not found, could not convert Markdown to RST
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-h0rz8b1_/deap/setup.py", line 22, in <module>
        long_description=read_md('README.md'),
      File "/tmp/pip-build-h0rz8b1_/deap/setup.py", line 13, in <lambda>
        read_md = lambda f: open(f, 'r').read()
      File "/root/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4945: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h0rz8b1_/deap
```

**Comment by cmd-ntrf** [comment]
@elazar Could you check the content of the variable $LANG in your shell? If it is something else than xxx.utf8, the setup will fail as it is in version 1.0.2.post2. The reason is Python used the shell encoding instead of checking the file encoding.

@soravux has fixed this is the master branch, however the fix has not been released yet.
https://github.com/DEAP/deap/commit/0424dc6b7a0489fa5cbb9d0482326745b6176c27

**Comment by elazar** [comment]
@cmd-ntrf By default, `$LANG` is empty. I tried explicitly setting it to `en_US.utf8`, `en_US.UTF8`, `en_US.UTF-8`, but I still get the same error in all cases. :disappointed:

**Comment by cmd-ntrf** [comment]
@elazar could you install pypandoc? `pip install pypandoc`. It would avoid the `ImportError` exception and the faulty code that assumes the default encoding will be UTF-8 on all platforms. In the mean time, I will try to release a new version that include the patch by @soravux.

Sorry for your troubles.

**Comment by shayanrc** [comment]
I encountered this issue recently (September 2017) while installing deap in a docker instance.

**Comment by gte620v** [comment]
me too

**Comment by Gab0** [comment]
@shayanrc  @gte620v  Installing pandoc, and then pypandoc from pip solved this issue on docker for me.
