### ISSUE TITLE
varAnd() and varOr() don't use toolbox.map

### ISSUE THREAD

**Issue by zachmoshe** [DEAP/deap#90]
I've noticed that varAnd and varOr functions don't use toolbox.map to generate the population but rather use a regular for loop. Is there any reason not to allow parallelization if the user chooses to register `pool.map` as his `map` function?

**Comment by fmder** [comment]
Parallel population generation leads to a much more complicated loop, and most of the users won't see any time difference. For this reason it didn't made it to the library.

Maybe you can PR an example of parallel population generation ad we will incorporate it to the documentation.

Cheers

**Comment by fmder** [comment]
The varAnd and varOr don't use toolbox.map for crossover ant mutation by
design. This would complexify the code and slow down (or at least won't add
speedup to) the algorithms for 99% of the users. We prefer users that need
this option to copy the var* code and implement it on there own.

Regards,
François-Michel

2015-08-09 11:01 GMT-04:00 Zach Moshe <notifications@github.com>:
