### ISSUE TITLE
add constrain when mutation

### ISSUE THREAD

**Issue by wangxiangtao** [DEAP/deap#95]
I have 3 genes(attribute) in each individual , for each gene has different constrain as below

toolbox.register("attr_para1", random.randint, 1, 3)
toolbox.register("attr_para2", random.randint, 1, 5)
toolbox.register("attr_para3", random.randint, 2, 10)

when do the mutation,  how to make sure the new individual use above constrain condition ?
toolbox.register("mutate", tools.mutUniformInt,low= ? , up = ?,  indpb=0.10)

How to set the parameter "low" and "up" , since there are more than one attribute  ? 

Thanks

**Comment by fmder** [comment]
low and up can be sequences, which will be applied to their respective
position.

http://deap.readthedocs.org/en/master/api/tools.html#deap.tools.mutUniformInt

Regards,

2015-10-03 1:46 GMT-04:00 wangxiangtao <notifications@github.com>:

**Comment by fmder** [comment]
For questions please use the deap-users google group.
